-- AUTO-GENERATED by oracle/data_engine/omega_ladder/codegen.py (emit_lean_proof_multifile).
-- Certified kill-tree for omega = 6: 3*phi(n) = 2n+2 has NO solution with 6 distinct prime factors.
-- Part of a genuinely parallel-compilable cross-file split -- see emit_lean_proof_multifile's docstring.
-- Chunk 2/5 (omega6_chunk_4): LEAF -- depends only on OmegaTreeSupport/SolutionStructure,
-- never on a sibling chunk. Safe to compile in parallel with every other leaf chunk.
import SolutionStructure
import OmegaTreeSupport

namespace EG411Structure

set_option linter.style.nativeDecide false

set_option maxRecDepth 8000 in
set_option maxHeartbeats 0 in
theorem omega6_chunk_4 (n : ℕ) (hn : 3 * Nat.totient n = 2 * n + 2)
    (p4 p5 p6 : ℕ) (hp4 : p4.Prime) (hp5 : p5.Prime) (hp6 : p6.Prime)
    (h3 : (47:ℕ) < p4) (h4 : p4 < p5) (h5 : p5 < p6)
    (hd1 : (5:ℕ) ∣ n) (hd2 : (7:ℕ) ∣ n) (hd3 : (47:ℕ) ∣ n) (hd4 : p4 ∣ n) (hd5 : p5 ∣ n)
    (heq3 : 3312 * ((p4 - 1) * ((p5 - 1) * (p6 - 1))) = 3290 * (p4 * (p5 * p6)) + 2) : False := by
  have hchain := solution_no_prime_chain hn
  have hcap3 : p4 < 457 := by
    by_contra hge
    exact cap_kill_3 (c := 457) (by norm_num) (by norm_num) (by omega)
      h4.le h5.le heq3
  have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
    hchain 5 p4 (by norm_num) hp4 hd1 hd4
  have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
    hchain 7 p4 (by norm_num) hp4 hd2 hd4
  have hch3_47 : ¬ (47:ℕ) ∣ (p4 - 1) :=
    hchain 47 p4 (by norm_num) hp4 hd3 hd4
  have hmem3 : p4 ∈ (Finset.Ioo 47 457).filter
      (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 47 ∣ (v - 1)) :=
    Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_7, hch3_47⟩
  have hset3 : (Finset.Ioo 47 457).filter
      (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 47 ∣ (v - 1))
      = ({53, 59, 67, 73, 79, 83, 89, 97,
          103, 107, 109, 137, 139, 149, 157, 163, 167, 173, 179, 193, 199, 223, 227, 229, 233, 257, 263, 269, 277, 293, 307, 313, 317, 347, 349, 353, 359, 367, 373, 383, 389, 397, 409, 419, 433, 439, 443} : Finset ℕ) := by native_decide
  rw [hset3] at hmem3
  fin_cases hmem3
  · -- p4 = 53
    have heq4 : 172224 * ((p5 - 1) * (p6 - 1))
        = 174370 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 59
    have heq4 : 192096 * ((p5 - 1) * (p6 - 1))
        = 194110 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 67
    have heq4 : 218592 * ((p5 - 1) * (p6 - 1))
        = 220430 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 73
    have heq4 : 238464 * ((p5 - 1) * (p6 - 1))
        = 240170 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 79
    have heq4 : 258336 * ((p5 - 1) * (p6 - 1))
        = 259910 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 83
    have heq4 : 271584 * ((p5 - 1) * (p6 - 1))
        = 273070 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 89
    have heq4 : 291456 * ((p5 - 1) * (p6 - 1))
        = 292810 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 97
    have heq4 : 317952 * ((p5 - 1) * (p6 - 1))
        = 319130 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 103
    have heq4 : 337824 * ((p5 - 1) * (p6 - 1))
        = 338870 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 107
    have heq4 : 351072 * ((p5 - 1) * (p6 - 1))
        = 352030 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 109
    have heq4 : 357696 * ((p5 - 1) * (p6 - 1))
        = 358610 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 137
    have heq4 : 450432 * ((p5 - 1) * (p6 - 1))
        = 450730 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 139
    have heq4 : 457056 * ((p5 - 1) * (p6 - 1))
        = 457310 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 149
    have heq4 : 490176 * ((p5 - 1) * (p6 - 1))
        = 490210 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 157
    have heq4 : 516672 * ((p5 - 1) * (p6 - 1))
        = 516530 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 7278 := by nlinarith [hbnd]
    by_cases hden : 516672 < (516672 - 516530) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_157 : ¬ (157:ℕ) ∣ (p5 - 1) :=
        hchain 157 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 157 7278).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 157 ∣ (v - 1) ∧
            ((516672 - 516530) * v - 516672) ∣ (516672 * v - 516672 + 2) ∧
            Nat.Prime ((516672 * v - 516672 + 2) / ((516672 - 516530) * v - 516672)) ∧
            v < (516672 * v - 516672 + 2) / ((516672 - 516530) * v - 516672)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_157, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 157 7278).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 157 ∣ (v - 1) ∧
            ((516672 - 516530) * v - 516672) ∣ (516672 * v - 516672 + 2) ∧
            Nat.Prime ((516672 * v - 516672 + 2) / ((516672 - 516530) * v - 516672)) ∧
            v < (516672 * v - 516672 + 2) / ((516672 - 516530) * v - 516672))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 163
    have heq4 : 536544 * ((p5 - 1) * (p6 - 1))
        = 536270 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 3917 := by nlinarith [hbnd]
    by_cases hden : 536544 < (536544 - 536270) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_163 : ¬ (163:ℕ) ∣ (p5 - 1) :=
        hchain 163 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 163 3917).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 163 ∣ (v - 1) ∧
            ((536544 - 536270) * v - 536544) ∣ (536544 * v - 536544 + 2) ∧
            Nat.Prime ((536544 * v - 536544 + 2) / ((536544 - 536270) * v - 536544)) ∧
            v < (536544 * v - 536544 + 2) / ((536544 - 536270) * v - 536544)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_163, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 163 3917).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 163 ∣ (v - 1) ∧
            ((536544 - 536270) * v - 536544) ∣ (536544 * v - 536544 + 2) ∧
            Nat.Prime ((536544 * v - 536544 + 2) / ((536544 - 536270) * v - 536544)) ∧
            v < (536544 * v - 536544 + 2) / ((536544 - 536270) * v - 536544))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 167
    have heq4 : 549792 * ((p5 - 1) * (p6 - 1))
        = 549430 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 3039 := by nlinarith [hbnd]
    by_cases hden : 549792 < (549792 - 549430) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_167 : ¬ (167:ℕ) ∣ (p5 - 1) :=
        hchain 167 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 167 3039).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 167 ∣ (v - 1) ∧
            ((549792 - 549430) * v - 549792) ∣ (549792 * v - 549792 + 2) ∧
            Nat.Prime ((549792 * v - 549792 + 2) / ((549792 - 549430) * v - 549792)) ∧
            v < (549792 * v - 549792 + 2) / ((549792 - 549430) * v - 549792)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_167, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 167 3039).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 167 ∣ (v - 1) ∧
            ((549792 - 549430) * v - 549792) ∣ (549792 * v - 549792 + 2) ∧
            Nat.Prime ((549792 * v - 549792 + 2) / ((549792 - 549430) * v - 549792)) ∧
            v < (549792 * v - 549792 + 2) / ((549792 - 549430) * v - 549792))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 173
    have heq4 : 569664 * ((p5 - 1) * (p6 - 1))
        = 569170 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 2307 := by nlinarith [hbnd]
    by_cases hden : 569664 < (569664 - 569170) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_173 : ¬ (173:ℕ) ∣ (p5 - 1) :=
        hchain 173 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 173 2307).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 173 ∣ (v - 1) ∧
            ((569664 - 569170) * v - 569664) ∣ (569664 * v - 569664 + 2) ∧
            Nat.Prime ((569664 * v - 569664 + 2) / ((569664 - 569170) * v - 569664)) ∧
            v < (569664 * v - 569664 + 2) / ((569664 - 569170) * v - 569664)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_173, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 173 2307).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 173 ∣ (v - 1) ∧
            ((569664 - 569170) * v - 569664) ∣ (569664 * v - 569664 + 2) ∧
            Nat.Prime ((569664 * v - 569664 + 2) / ((569664 - 569170) * v - 569664)) ∧
            v < (569664 * v - 569664 + 2) / ((569664 - 569170) * v - 569664))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 179
    have heq4 : 589536 * ((p5 - 1) * (p6 - 1))
        = 588910 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 1885 := by nlinarith [hbnd]
    by_cases hden : 589536 < (589536 - 588910) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_179 : ¬ (179:ℕ) ∣ (p5 - 1) :=
        hchain 179 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 179 1885).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 179 ∣ (v - 1) ∧
            ((589536 - 588910) * v - 589536) ∣ (589536 * v - 589536 + 2) ∧
            Nat.Prime ((589536 * v - 589536 + 2) / ((589536 - 588910) * v - 589536)) ∧
            v < (589536 * v - 589536 + 2) / ((589536 - 588910) * v - 589536)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_179, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 179 1885).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 179 ∣ (v - 1) ∧
            ((589536 - 588910) * v - 589536) ∣ (589536 * v - 589536 + 2) ∧
            Nat.Prime ((589536 * v - 589536 + 2) / ((589536 - 588910) * v - 589536)) ∧
            v < (589536 * v - 589536 + 2) / ((589536 - 588910) * v - 589536))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 193
    have heq4 : 635904 * ((p5 - 1) * (p6 - 1))
        = 634970 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 1363 := by nlinarith [hbnd]
    by_cases hden : 635904 < (635904 - 634970) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_193 : ¬ (193:ℕ) ∣ (p5 - 1) :=
        hchain 193 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 193 1363).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 193 ∣ (v - 1) ∧
            ((635904 - 634970) * v - 635904) ∣ (635904 * v - 635904 + 2) ∧
            Nat.Prime ((635904 * v - 635904 + 2) / ((635904 - 634970) * v - 635904)) ∧
            v < (635904 * v - 635904 + 2) / ((635904 - 634970) * v - 635904)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_193, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 193 1363).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 193 ∣ (v - 1) ∧
            ((635904 - 634970) * v - 635904) ∣ (635904 * v - 635904 + 2) ∧
            Nat.Prime ((635904 * v - 635904 + 2) / ((635904 - 634970) * v - 635904)) ∧
            v < (635904 * v - 635904 + 2) / ((635904 - 634970) * v - 635904))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 199
    have heq4 : 655776 * ((p5 - 1) * (p6 - 1))
        = 654710 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 1231 := by nlinarith [hbnd]
    by_cases hden : 655776 < (655776 - 654710) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_199 : ¬ (199:ℕ) ∣ (p5 - 1) :=
        hchain 199 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 199 1231).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 199 ∣ (v - 1) ∧
            ((655776 - 654710) * v - 655776) ∣ (655776 * v - 655776 + 2) ∧
            Nat.Prime ((655776 * v - 655776 + 2) / ((655776 - 654710) * v - 655776)) ∧
            v < (655776 * v - 655776 + 2) / ((655776 - 654710) * v - 655776)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_199, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 199 1231).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 199 ∣ (v - 1) ∧
            ((655776 - 654710) * v - 655776) ∣ (655776 * v - 655776 + 2) ∧
            Nat.Prime ((655776 * v - 655776 + 2) / ((655776 - 654710) * v - 655776)) ∧
            v < (655776 * v - 655776 + 2) / ((655776 - 654710) * v - 655776))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 223
    have heq4 : 735264 * ((p5 - 1) * (p6 - 1))
        = 733670 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 924 := by nlinarith [hbnd]
    by_cases hden : 735264 < (735264 - 733670) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_223 : ¬ (223:ℕ) ∣ (p5 - 1) :=
        hchain 223 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 223 924).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 223 ∣ (v - 1) ∧
            ((735264 - 733670) * v - 735264) ∣ (735264 * v - 735264 + 2) ∧
            Nat.Prime ((735264 * v - 735264 + 2) / ((735264 - 733670) * v - 735264)) ∧
            v < (735264 * v - 735264 + 2) / ((735264 - 733670) * v - 735264)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_223, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 223 924).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 223 ∣ (v - 1) ∧
            ((735264 - 733670) * v - 735264) ∣ (735264 * v - 735264 + 2) ∧
            Nat.Prime ((735264 * v - 735264 + 2) / ((735264 - 733670) * v - 735264)) ∧
            v < (735264 * v - 735264 + 2) / ((735264 - 733670) * v - 735264))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 227
    have heq4 : 748512 * ((p5 - 1) * (p6 - 1))
        = 746830 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 891 := by nlinarith [hbnd]
    by_cases hden : 748512 < (748512 - 746830) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_227 : ¬ (227:ℕ) ∣ (p5 - 1) :=
        hchain 227 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 227 891).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 227 ∣ (v - 1) ∧
            ((748512 - 746830) * v - 748512) ∣ (748512 * v - 748512 + 2) ∧
            Nat.Prime ((748512 * v - 748512 + 2) / ((748512 - 746830) * v - 748512)) ∧
            v < (748512 * v - 748512 + 2) / ((748512 - 746830) * v - 748512)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_227, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 227 891).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 227 ∣ (v - 1) ∧
            ((748512 - 746830) * v - 748512) ∣ (748512 * v - 748512 + 2) ∧
            Nat.Prime ((748512 * v - 748512 + 2) / ((748512 - 746830) * v - 748512)) ∧
            v < (748512 * v - 748512 + 2) / ((748512 - 746830) * v - 748512))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 229
    have heq4 : 755136 * ((p5 - 1) * (p6 - 1))
        = 753410 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 876 := by nlinarith [hbnd]
    by_cases hden : 755136 < (755136 - 753410) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_229 : ¬ (229:ℕ) ∣ (p5 - 1) :=
        hchain 229 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 229 876).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 229 ∣ (v - 1) ∧
            ((755136 - 753410) * v - 755136) ∣ (755136 * v - 755136 + 2) ∧
            Nat.Prime ((755136 * v - 755136 + 2) / ((755136 - 753410) * v - 755136)) ∧
            v < (755136 * v - 755136 + 2) / ((755136 - 753410) * v - 755136)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_229, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 229 876).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 229 ∣ (v - 1) ∧
            ((755136 - 753410) * v - 755136) ∣ (755136 * v - 755136 + 2) ∧
            Nat.Prime ((755136 * v - 755136 + 2) / ((755136 - 753410) * v - 755136)) ∧
            v < (755136 * v - 755136 + 2) / ((755136 - 753410) * v - 755136))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 233
    have heq4 : 768384 * ((p5 - 1) * (p6 - 1))
        = 766570 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 848 := by nlinarith [hbnd]
    by_cases hden : 768384 < (768384 - 766570) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_233 : ¬ (233:ℕ) ∣ (p5 - 1) :=
        hchain 233 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 233 848).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 233 ∣ (v - 1) ∧
            ((768384 - 766570) * v - 768384) ∣ (768384 * v - 768384 + 2) ∧
            Nat.Prime ((768384 * v - 768384 + 2) / ((768384 - 766570) * v - 768384)) ∧
            v < (768384 * v - 768384 + 2) / ((768384 - 766570) * v - 768384)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_233, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 233 848).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 233 ∣ (v - 1) ∧
            ((768384 - 766570) * v - 768384) ∣ (768384 * v - 768384 + 2) ∧
            Nat.Prime ((768384 * v - 768384 + 2) / ((768384 - 766570) * v - 768384)) ∧
            v < (768384 * v - 768384 + 2) / ((768384 - 766570) * v - 768384))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 257
    have heq4 : 847872 * ((p5 - 1) * (p6 - 1))
        = 845530 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 725 := by nlinarith [hbnd]
    by_cases hden : 847872 < (847872 - 845530) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_257 : ¬ (257:ℕ) ∣ (p5 - 1) :=
        hchain 257 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 257 725).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 257 ∣ (v - 1) ∧
            ((847872 - 845530) * v - 847872) ∣ (847872 * v - 847872 + 2) ∧
            Nat.Prime ((847872 * v - 847872 + 2) / ((847872 - 845530) * v - 847872)) ∧
            v < (847872 * v - 847872 + 2) / ((847872 - 845530) * v - 847872)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_257, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 257 725).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 257 ∣ (v - 1) ∧
            ((847872 - 845530) * v - 847872) ∣ (847872 * v - 847872 + 2) ∧
            Nat.Prime ((847872 * v - 847872 + 2) / ((847872 - 845530) * v - 847872)) ∧
            v < (847872 * v - 847872 + 2) / ((847872 - 845530) * v - 847872))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 263
    have heq4 : 867744 * ((p5 - 1) * (p6 - 1))
        = 865270 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 702 := by nlinarith [hbnd]
    by_cases hden : 867744 < (867744 - 865270) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_263 : ¬ (263:ℕ) ∣ (p5 - 1) :=
        hchain 263 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 263 702).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 263 ∣ (v - 1) ∧
            ((867744 - 865270) * v - 867744) ∣ (867744 * v - 867744 + 2) ∧
            Nat.Prime ((867744 * v - 867744 + 2) / ((867744 - 865270) * v - 867744)) ∧
            v < (867744 * v - 867744 + 2) / ((867744 - 865270) * v - 867744)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_263, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 263 702).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 263 ∣ (v - 1) ∧
            ((867744 - 865270) * v - 867744) ∣ (867744 * v - 867744 + 2) ∧
            Nat.Prime ((867744 * v - 867744 + 2) / ((867744 - 865270) * v - 867744)) ∧
            v < (867744 * v - 867744 + 2) / ((867744 - 865270) * v - 867744))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 269
    have heq4 : 887616 * ((p5 - 1) * (p6 - 1))
        = 885010 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 682 := by nlinarith [hbnd]
    by_cases hden : 887616 < (887616 - 885010) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_269 : ¬ (269:ℕ) ∣ (p5 - 1) :=
        hchain 269 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 269 682).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 269 ∣ (v - 1) ∧
            ((887616 - 885010) * v - 887616) ∣ (887616 * v - 887616 + 2) ∧
            Nat.Prime ((887616 * v - 887616 + 2) / ((887616 - 885010) * v - 887616)) ∧
            v < (887616 * v - 887616 + 2) / ((887616 - 885010) * v - 887616)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_269, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 269 682).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 269 ∣ (v - 1) ∧
            ((887616 - 885010) * v - 887616) ∣ (887616 * v - 887616 + 2) ∧
            Nat.Prime ((887616 * v - 887616 + 2) / ((887616 - 885010) * v - 887616)) ∧
            v < (887616 * v - 887616 + 2) / ((887616 - 885010) * v - 887616))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 277
    have heq4 : 914112 * ((p5 - 1) * (p6 - 1))
        = 911330 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 658 := by nlinarith [hbnd]
    by_cases hden : 914112 < (914112 - 911330) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_277 : ¬ (277:ℕ) ∣ (p5 - 1) :=
        hchain 277 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 277 658).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 277 ∣ (v - 1) ∧
            ((914112 - 911330) * v - 914112) ∣ (914112 * v - 914112 + 2) ∧
            Nat.Prime ((914112 * v - 914112 + 2) / ((914112 - 911330) * v - 914112)) ∧
            v < (914112 * v - 914112 + 2) / ((914112 - 911330) * v - 914112)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_277, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 277 658).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 277 ∣ (v - 1) ∧
            ((914112 - 911330) * v - 914112) ∣ (914112 * v - 914112 + 2) ∧
            Nat.Prime ((914112 * v - 914112 + 2) / ((914112 - 911330) * v - 914112)) ∧
            v < (914112 * v - 914112 + 2) / ((914112 - 911330) * v - 914112))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 293
    have heq4 : 967104 * ((p5 - 1) * (p6 - 1))
        = 963970 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 618 := by nlinarith [hbnd]
    by_cases hden : 967104 < (967104 - 963970) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_293 : ¬ (293:ℕ) ∣ (p5 - 1) :=
        hchain 293 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 293 618).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 293 ∣ (v - 1) ∧
            ((967104 - 963970) * v - 967104) ∣ (967104 * v - 967104 + 2) ∧
            Nat.Prime ((967104 * v - 967104 + 2) / ((967104 - 963970) * v - 967104)) ∧
            v < (967104 * v - 967104 + 2) / ((967104 - 963970) * v - 967104)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_293, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 293 618).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 293 ∣ (v - 1) ∧
            ((967104 - 963970) * v - 967104) ∣ (967104 * v - 967104 + 2) ∧
            Nat.Prime ((967104 * v - 967104 + 2) / ((967104 - 963970) * v - 967104)) ∧
            v < (967104 * v - 967104 + 2) / ((967104 - 963970) * v - 967104))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 307
    have heq4 : 1013472 * ((p5 - 1) * (p6 - 1))
        = 1010030 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 590 := by nlinarith [hbnd]
    by_cases hden : 1013472 < (1013472 - 1010030) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_307 : ¬ (307:ℕ) ∣ (p5 - 1) :=
        hchain 307 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 307 590).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 307 ∣ (v - 1) ∧
            ((1013472 - 1010030) * v - 1013472) ∣ (1013472 * v - 1013472 + 2) ∧
            Nat.Prime ((1013472 * v - 1013472 + 2) / ((1013472 - 1010030) * v - 1013472)) ∧
            v < (1013472 * v - 1013472 + 2) / ((1013472 - 1010030) * v - 1013472)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_307, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 307 590).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 307 ∣ (v - 1) ∧
            ((1013472 - 1010030) * v - 1013472) ∣ (1013472 * v - 1013472 + 2) ∧
            Nat.Prime ((1013472 * v - 1013472 + 2) / ((1013472 - 1010030) * v - 1013472)) ∧
            v < (1013472 * v - 1013472 + 2) / ((1013472 - 1010030) * v - 1013472))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 313
    have heq4 : 1033344 * ((p5 - 1) * (p6 - 1))
        = 1029770 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 579 := by nlinarith [hbnd]
    by_cases hden : 1033344 < (1033344 - 1029770) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_313 : ¬ (313:ℕ) ∣ (p5 - 1) :=
        hchain 313 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 313 579).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 313 ∣ (v - 1) ∧
            ((1033344 - 1029770) * v - 1033344) ∣ (1033344 * v - 1033344 + 2) ∧
            Nat.Prime ((1033344 * v - 1033344 + 2) / ((1033344 - 1029770) * v - 1033344)) ∧
            v < (1033344 * v - 1033344 + 2) / ((1033344 - 1029770) * v - 1033344)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_313, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 313 579).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 313 ∣ (v - 1) ∧
            ((1033344 - 1029770) * v - 1033344) ∣ (1033344 * v - 1033344 + 2) ∧
            Nat.Prime ((1033344 * v - 1033344 + 2) / ((1033344 - 1029770) * v - 1033344)) ∧
            v < (1033344 * v - 1033344 + 2) / ((1033344 - 1029770) * v - 1033344))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 317
    have heq4 : 1046592 * ((p5 - 1) * (p6 - 1))
        = 1042930 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 573 := by nlinarith [hbnd]
    by_cases hden : 1046592 < (1046592 - 1042930) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_317 : ¬ (317:ℕ) ∣ (p5 - 1) :=
        hchain 317 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 317 573).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 317 ∣ (v - 1) ∧
            ((1046592 - 1042930) * v - 1046592) ∣ (1046592 * v - 1046592 + 2) ∧
            Nat.Prime ((1046592 * v - 1046592 + 2) / ((1046592 - 1042930) * v - 1046592)) ∧
            v < (1046592 * v - 1046592 + 2) / ((1046592 - 1042930) * v - 1046592)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_317, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 317 573).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 317 ∣ (v - 1) ∧
            ((1046592 - 1042930) * v - 1046592) ∣ (1046592 * v - 1046592 + 2) ∧
            Nat.Prime ((1046592 * v - 1046592 + 2) / ((1046592 - 1042930) * v - 1046592)) ∧
            v < (1046592 * v - 1046592 + 2) / ((1046592 - 1042930) * v - 1046592))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 347
    have heq4 : 1145952 * ((p5 - 1) * (p6 - 1))
        = 1141630 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 531 := by nlinarith [hbnd]
    by_cases hden : 1145952 < (1145952 - 1141630) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_347 : ¬ (347:ℕ) ∣ (p5 - 1) :=
        hchain 347 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 347 531).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 347 ∣ (v - 1) ∧
            ((1145952 - 1141630) * v - 1145952) ∣ (1145952 * v - 1145952 + 2) ∧
            Nat.Prime ((1145952 * v - 1145952 + 2) / ((1145952 - 1141630) * v - 1145952)) ∧
            v < (1145952 * v - 1145952 + 2) / ((1145952 - 1141630) * v - 1145952)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_347, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 347 531).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 347 ∣ (v - 1) ∧
            ((1145952 - 1141630) * v - 1145952) ∣ (1145952 * v - 1145952 + 2) ∧
            Nat.Prime ((1145952 * v - 1145952 + 2) / ((1145952 - 1141630) * v - 1145952)) ∧
            v < (1145952 * v - 1145952 + 2) / ((1145952 - 1141630) * v - 1145952))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 349
    have heq4 : 1152576 * ((p5 - 1) * (p6 - 1))
        = 1148210 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 529 := by nlinarith [hbnd]
    by_cases hden : 1152576 < (1152576 - 1148210) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_349 : ¬ (349:ℕ) ∣ (p5 - 1) :=
        hchain 349 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 349 529).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 349 ∣ (v - 1) ∧
            ((1152576 - 1148210) * v - 1152576) ∣ (1152576 * v - 1152576 + 2) ∧
            Nat.Prime ((1152576 * v - 1152576 + 2) / ((1152576 - 1148210) * v - 1152576)) ∧
            v < (1152576 * v - 1152576 + 2) / ((1152576 - 1148210) * v - 1152576)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_349, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 349 529).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 349 ∣ (v - 1) ∧
            ((1152576 - 1148210) * v - 1152576) ∣ (1152576 * v - 1152576 + 2) ∧
            Nat.Prime ((1152576 * v - 1152576 + 2) / ((1152576 - 1148210) * v - 1152576)) ∧
            v < (1152576 * v - 1152576 + 2) / ((1152576 - 1148210) * v - 1152576))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 353
    have heq4 : 1165824 * ((p5 - 1) * (p6 - 1))
        = 1161370 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 524 := by nlinarith [hbnd]
    by_cases hden : 1165824 < (1165824 - 1161370) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_353 : ¬ (353:ℕ) ∣ (p5 - 1) :=
        hchain 353 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 353 524).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 353 ∣ (v - 1) ∧
            ((1165824 - 1161370) * v - 1165824) ∣ (1165824 * v - 1165824 + 2) ∧
            Nat.Prime ((1165824 * v - 1165824 + 2) / ((1165824 - 1161370) * v - 1165824)) ∧
            v < (1165824 * v - 1165824 + 2) / ((1165824 - 1161370) * v - 1165824)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_353, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 353 524).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 353 ∣ (v - 1) ∧
            ((1165824 - 1161370) * v - 1165824) ∣ (1165824 * v - 1165824 + 2) ∧
            Nat.Prime ((1165824 * v - 1165824 + 2) / ((1165824 - 1161370) * v - 1165824)) ∧
            v < (1165824 * v - 1165824 + 2) / ((1165824 - 1161370) * v - 1165824))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 359
    have heq4 : 1185696 * ((p5 - 1) * (p6 - 1))
        = 1181110 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 518 := by nlinarith [hbnd]
    by_cases hden : 1185696 < (1185696 - 1181110) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_359 : ¬ (359:ℕ) ∣ (p5 - 1) :=
        hchain 359 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 359 518).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 359 ∣ (v - 1) ∧
            ((1185696 - 1181110) * v - 1185696) ∣ (1185696 * v - 1185696 + 2) ∧
            Nat.Prime ((1185696 * v - 1185696 + 2) / ((1185696 - 1181110) * v - 1185696)) ∧
            v < (1185696 * v - 1185696 + 2) / ((1185696 - 1181110) * v - 1185696)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_359, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 359 518).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 359 ∣ (v - 1) ∧
            ((1185696 - 1181110) * v - 1185696) ∣ (1185696 * v - 1185696 + 2) ∧
            Nat.Prime ((1185696 * v - 1185696 + 2) / ((1185696 - 1181110) * v - 1185696)) ∧
            v < (1185696 * v - 1185696 + 2) / ((1185696 - 1181110) * v - 1185696))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 367
    have heq4 : 1212192 * ((p5 - 1) * (p6 - 1))
        = 1207430 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 510 := by nlinarith [hbnd]
    by_cases hden : 1212192 < (1212192 - 1207430) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_367 : ¬ (367:ℕ) ∣ (p5 - 1) :=
        hchain 367 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 367 510).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 367 ∣ (v - 1) ∧
            ((1212192 - 1207430) * v - 1212192) ∣ (1212192 * v - 1212192 + 2) ∧
            Nat.Prime ((1212192 * v - 1212192 + 2) / ((1212192 - 1207430) * v - 1212192)) ∧
            v < (1212192 * v - 1212192 + 2) / ((1212192 - 1207430) * v - 1212192)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_367, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 367 510).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 367 ∣ (v - 1) ∧
            ((1212192 - 1207430) * v - 1212192) ∣ (1212192 * v - 1212192 + 2) ∧
            Nat.Prime ((1212192 * v - 1212192 + 2) / ((1212192 - 1207430) * v - 1212192)) ∧
            v < (1212192 * v - 1212192 + 2) / ((1212192 - 1207430) * v - 1212192))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 373
    have heq4 : 1232064 * ((p5 - 1) * (p6 - 1))
        = 1227170 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 504 := by nlinarith [hbnd]
    by_cases hden : 1232064 < (1232064 - 1227170) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_373 : ¬ (373:ℕ) ∣ (p5 - 1) :=
        hchain 373 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 373 504).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 373 ∣ (v - 1) ∧
            ((1232064 - 1227170) * v - 1232064) ∣ (1232064 * v - 1232064 + 2) ∧
            Nat.Prime ((1232064 * v - 1232064 + 2) / ((1232064 - 1227170) * v - 1232064)) ∧
            v < (1232064 * v - 1232064 + 2) / ((1232064 - 1227170) * v - 1232064)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_373, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 373 504).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 373 ∣ (v - 1) ∧
            ((1232064 - 1227170) * v - 1232064) ∣ (1232064 * v - 1232064 + 2) ∧
            Nat.Prime ((1232064 * v - 1232064 + 2) / ((1232064 - 1227170) * v - 1232064)) ∧
            v < (1232064 * v - 1232064 + 2) / ((1232064 - 1227170) * v - 1232064))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 383
    have heq4 : 1265184 * ((p5 - 1) * (p6 - 1))
        = 1260070 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 496 := by nlinarith [hbnd]
    by_cases hden : 1265184 < (1265184 - 1260070) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_383 : ¬ (383:ℕ) ∣ (p5 - 1) :=
        hchain 383 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 383 496).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 383 ∣ (v - 1) ∧
            ((1265184 - 1260070) * v - 1265184) ∣ (1265184 * v - 1265184 + 2) ∧
            Nat.Prime ((1265184 * v - 1265184 + 2) / ((1265184 - 1260070) * v - 1265184)) ∧
            v < (1265184 * v - 1265184 + 2) / ((1265184 - 1260070) * v - 1265184)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_383, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 383 496).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 383 ∣ (v - 1) ∧
            ((1265184 - 1260070) * v - 1265184) ∣ (1265184 * v - 1265184 + 2) ∧
            Nat.Prime ((1265184 * v - 1265184 + 2) / ((1265184 - 1260070) * v - 1265184)) ∧
            v < (1265184 * v - 1265184 + 2) / ((1265184 - 1260070) * v - 1265184))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 389
    have heq4 : 1285056 * ((p5 - 1) * (p6 - 1))
        = 1279810 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 491 := by nlinarith [hbnd]
    by_cases hden : 1285056 < (1285056 - 1279810) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_389 : ¬ (389:ℕ) ∣ (p5 - 1) :=
        hchain 389 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 389 491).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 389 ∣ (v - 1) ∧
            ((1285056 - 1279810) * v - 1285056) ∣ (1285056 * v - 1285056 + 2) ∧
            Nat.Prime ((1285056 * v - 1285056 + 2) / ((1285056 - 1279810) * v - 1285056)) ∧
            v < (1285056 * v - 1285056 + 2) / ((1285056 - 1279810) * v - 1285056)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_389, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 389 491).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 389 ∣ (v - 1) ∧
            ((1285056 - 1279810) * v - 1285056) ∣ (1285056 * v - 1285056 + 2) ∧
            Nat.Prime ((1285056 * v - 1285056 + 2) / ((1285056 - 1279810) * v - 1285056)) ∧
            v < (1285056 * v - 1285056 + 2) / ((1285056 - 1279810) * v - 1285056))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 397
    have heq4 : 1311552 * ((p5 - 1) * (p6 - 1))
        = 1306130 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 485 := by nlinarith [hbnd]
    by_cases hden : 1311552 < (1311552 - 1306130) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_397 : ¬ (397:ℕ) ∣ (p5 - 1) :=
        hchain 397 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 397 485).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 397 ∣ (v - 1) ∧
            ((1311552 - 1306130) * v - 1311552) ∣ (1311552 * v - 1311552 + 2) ∧
            Nat.Prime ((1311552 * v - 1311552 + 2) / ((1311552 - 1306130) * v - 1311552)) ∧
            v < (1311552 * v - 1311552 + 2) / ((1311552 - 1306130) * v - 1311552)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_397, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 397 485).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 397 ∣ (v - 1) ∧
            ((1311552 - 1306130) * v - 1311552) ∣ (1311552 * v - 1311552 + 2) ∧
            Nat.Prime ((1311552 * v - 1311552 + 2) / ((1311552 - 1306130) * v - 1311552)) ∧
            v < (1311552 * v - 1311552 + 2) / ((1311552 - 1306130) * v - 1311552))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 409
    have heq4 : 1351296 * ((p5 - 1) * (p6 - 1))
        = 1345610 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 476 := by nlinarith [hbnd]
    by_cases hden : 1351296 < (1351296 - 1345610) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_409 : ¬ (409:ℕ) ∣ (p5 - 1) :=
        hchain 409 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 409 476).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 409 ∣ (v - 1) ∧
            ((1351296 - 1345610) * v - 1351296) ∣ (1351296 * v - 1351296 + 2) ∧
            Nat.Prime ((1351296 * v - 1351296 + 2) / ((1351296 - 1345610) * v - 1351296)) ∧
            v < (1351296 * v - 1351296 + 2) / ((1351296 - 1345610) * v - 1351296)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_409, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 409 476).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 409 ∣ (v - 1) ∧
            ((1351296 - 1345610) * v - 1351296) ∣ (1351296 * v - 1351296 + 2) ∧
            Nat.Prime ((1351296 * v - 1351296 + 2) / ((1351296 - 1345610) * v - 1351296)) ∧
            v < (1351296 * v - 1351296 + 2) / ((1351296 - 1345610) * v - 1351296))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 419
    have heq4 : 1384416 * ((p5 - 1) * (p6 - 1))
        = 1378510 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 470 := by nlinarith [hbnd]
    by_cases hden : 1384416 < (1384416 - 1378510) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_419 : ¬ (419:ℕ) ∣ (p5 - 1) :=
        hchain 419 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 419 470).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 419 ∣ (v - 1) ∧
            ((1384416 - 1378510) * v - 1384416) ∣ (1384416 * v - 1384416 + 2) ∧
            Nat.Prime ((1384416 * v - 1384416 + 2) / ((1384416 - 1378510) * v - 1384416)) ∧
            v < (1384416 * v - 1384416 + 2) / ((1384416 - 1378510) * v - 1384416)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_419, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 419 470).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 419 ∣ (v - 1) ∧
            ((1384416 - 1378510) * v - 1384416) ∣ (1384416 * v - 1384416 + 2) ∧
            Nat.Prime ((1384416 * v - 1384416 + 2) / ((1384416 - 1378510) * v - 1384416)) ∧
            v < (1384416 * v - 1384416 + 2) / ((1384416 - 1378510) * v - 1384416))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 433
    have heq4 : 1430784 * ((p5 - 1) * (p6 - 1))
        = 1424570 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 462 := by nlinarith [hbnd]
    by_cases hden : 1430784 < (1430784 - 1424570) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_433 : ¬ (433:ℕ) ∣ (p5 - 1) :=
        hchain 433 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 433 462).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 433 ∣ (v - 1) ∧
            ((1430784 - 1424570) * v - 1430784) ∣ (1430784 * v - 1430784 + 2) ∧
            Nat.Prime ((1430784 * v - 1430784 + 2) / ((1430784 - 1424570) * v - 1430784)) ∧
            v < (1430784 * v - 1430784 + 2) / ((1430784 - 1424570) * v - 1430784)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_433, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 433 462).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 433 ∣ (v - 1) ∧
            ((1430784 - 1424570) * v - 1430784) ∣ (1430784 * v - 1430784 + 2) ∧
            Nat.Prime ((1430784 * v - 1430784 + 2) / ((1430784 - 1424570) * v - 1430784)) ∧
            v < (1430784 * v - 1430784 + 2) / ((1430784 - 1424570) * v - 1430784))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 439
    have heq4 : 1450656 * ((p5 - 1) * (p6 - 1))
        = 1444310 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 458 := by nlinarith [hbnd]
    by_cases hden : 1450656 < (1450656 - 1444310) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_439 : ¬ (439:ℕ) ∣ (p5 - 1) :=
        hchain 439 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 439 458).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 439 ∣ (v - 1) ∧
            ((1450656 - 1444310) * v - 1450656) ∣ (1450656 * v - 1450656 + 2) ∧
            Nat.Prime ((1450656 * v - 1450656 + 2) / ((1450656 - 1444310) * v - 1450656)) ∧
            v < (1450656 * v - 1450656 + 2) / ((1450656 - 1444310) * v - 1450656)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_439, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 439 458).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 439 ∣ (v - 1) ∧
            ((1450656 - 1444310) * v - 1450656) ∣ (1450656 * v - 1450656 + 2) ∧
            Nat.Prime ((1450656 * v - 1450656 + 2) / ((1450656 - 1444310) * v - 1450656)) ∧
            v < (1450656 * v - 1450656 + 2) / ((1450656 - 1444310) * v - 1450656))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 443
    have heq4 : 1463904 * ((p5 - 1) * (p6 - 1))
        = 1457470 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 456 := by nlinarith [hbnd]
    by_cases hden : 1463904 < (1463904 - 1457470) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
        hchain 47 p5 (by norm_num) hp5 hd3 hd5
      have hch4_443 : ¬ (443:ℕ) ∣ (p5 - 1) :=
        hchain 443 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 443 456).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 443 ∣ (v - 1) ∧
            ((1463904 - 1457470) * v - 1463904) ∣ (1463904 * v - 1463904 + 2) ∧
            Nat.Prime ((1463904 * v - 1463904 + 2) / ((1463904 - 1457470) * v - 1463904)) ∧
            v < (1463904 * v - 1463904 + 2) / ((1463904 - 1457470) * v - 1463904)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_47, hch4_443, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 443 456).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 47 ∣ (v - 1) ∧
            ¬ 443 ∣ (v - 1) ∧
            ((1463904 - 1457470) * v - 1463904) ∣ (1463904 * v - 1463904 + 2) ∧
            Nat.Prime ((1463904 * v - 1463904 + 2) / ((1463904 - 1457470) * v - 1463904)) ∧
            v < (1463904 * v - 1463904 + 2) / ((1463904 - 1457470) * v - 1463904))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)

end EG411Structure