-- AUTO-GENERATED by oracle/data_engine/omega_ladder/codegen.py (emit_lean_proof_multifile).
-- Certified kill-tree for omega = 6: 3*phi(n) = 2n+2 has NO solution with 6 distinct prime factors.
-- Part of a genuinely parallel-compilable cross-file split -- see emit_lean_proof_multifile's docstring.
-- Chunk 5/5 (omega6_chunk_1): NESTED -- its own subtree exceeded chunk_threshold
-- again, so it calls 1 further chunk(s) below. Depends on those chunks' .olean;
-- the orchestrator must compile them first (see lean-parallel-compile.ts's wave scheduling).
import SolutionStructure
import OmegaTreeSupport
import Omega6ChunkMF4

namespace EG411Structure

set_option linter.style.nativeDecide false

set_option maxRecDepth 8000 in
set_option maxHeartbeats 0 in
theorem omega6_chunk_1 (n : ℕ) (hn : 3 * Nat.totient n = 2 * n + 2)
    (p2 p3 p4 p5 p6 : ℕ) (hp2 : p2.Prime) (hp3 : p3.Prime) (hp4 : p4.Prime) (hp5 : p5.Prime) (hp6 : p6.Prime)
    (h1 : (5:ℕ) < p2) (h2 : p2 < p3) (h3 : p3 < p4) (h4 : p4 < p5) (h5 : p5 < p6)
    (hd1 : (5:ℕ) ∣ n) (hd2 : p2 ∣ n) (hd3 : p3 ∣ n) (hd4 : p4 ∣ n) (hd5 : p5 ∣ n)
    (heq1 : 12 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))) = 10 * (p2 * (p3 * (p4 * (p5 * p6)))) + 2) : False := by
  have hchain := solution_no_prime_chain hn
  have hcap1 : p2 < 29 := by
    by_contra hge
    exact cap_kill_5 (c := 29) (by norm_num) (by norm_num) (by omega)
      h2.le h3.le h4.le h5.le heq1
  have hch1_5 : ¬ (5:ℕ) ∣ (p2 - 1) :=
    hchain 5 p2 (by norm_num) hp2 hd1 hd2
  have hmem1 : p2 ∈ (Finset.Ioo 5 29).filter
      (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1)) :=
    Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_5⟩
  have hset1 : (Finset.Ioo 5 29).filter
      (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1))
      = ({7, 13, 17, 19, 23} : Finset ℕ) := by native_decide
  rw [hset1] at hmem1
  fin_cases hmem1
  · -- p2 = 7
    have heq2 : 72 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
        = 70 * (p3 * (p4 * (p5 * p6))) + 2 := by
      ring_nf at heq1 ⊢
      omega
    exact omega6_chunk_2 n hn p3 p4 p5 p6 hp3 hp4 hp5 hp6 h2 h3 h4 h5 hd1 hd2 hd3 hd4 hd5 heq2
  · -- p2 = 13
    have heq2 : 144 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
        = 130 * (p3 * (p4 * (p5 * p6))) + 2 := by
      ring_nf at heq1 ⊢
      omega
    have hcap2 : p3 < 41 := by
      by_contra hge
      exact cap_kill_4 (c := 41) (by norm_num) (by norm_num) (by omega)
        h3.le h4.le h5.le heq2
    have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
      hchain 5 p3 (by norm_num) hp3 hd1 hd3
    have hch2_13 : ¬ (13:ℕ) ∣ (p3 - 1) :=
      hchain 13 p3 (by norm_num) hp3 hd2 hd3
    have hmem2 : p3 ∈ (Finset.Ioo 13 41).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_13⟩
    have hset2 : (Finset.Ioo 13 41).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
        = ({17, 19, 23, 29, 37} : Finset ℕ) := by native_decide
    rw [hset2] at hmem2
    fin_cases hmem2
    · -- p3 = 17
      have heq3 : 2304 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 2210 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 73 := by
        by_contra hge
        exact cap_kill_3 (c := 73) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
        hchain 13 p4 (by norm_num) hp4 hd2 hd4
      have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
        hchain 17 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 17 73).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_13, hch3_17⟩
      have hset3 : (Finset.Ioo 17 73).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1))
          = ({19, 23, 29, 37, 43, 47, 59, 67} : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      fin_cases hmem3
      · -- p4 = 19
        have heq4 : 41472 * ((p5 - 1) * (p6 - 1))
            = 41990 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq4
      · -- p4 = 23
        have heq4 : 50688 * ((p5 - 1) * (p6 - 1))
            = 50830 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq4
      · -- p4 = 29
        have heq4 : 64512 * ((p5 - 1) * (p6 - 1))
            = 64090 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 307 := by nlinarith [hbnd]
        by_cases hden : 64512 < (64512 - 64090) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd3 hd5
          have hch4_29 : ¬ (29:ℕ) ∣ (p5 - 1) :=
            hchain 29 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 29 307).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((64512 - 64090) * v - 64512) ∣ (64512 * v - 64512 + 2) ∧
                Nat.Prime ((64512 * v - 64512 + 2) / ((64512 - 64090) * v - 64512)) ∧
                v < (64512 * v - 64512 + 2) / ((64512 - 64090) * v - 64512)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_17, hch4_29, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 29 307).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((64512 - 64090) * v - 64512) ∣ (64512 * v - 64512 + 2) ∧
                Nat.Prime ((64512 * v - 64512 + 2) / ((64512 - 64090) * v - 64512)) ∧
                v < (64512 * v - 64512 + 2) / ((64512 - 64090) * v - 64512))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 37
        have heq4 : 82944 * ((p5 - 1) * (p6 - 1))
            = 81770 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 142 := by nlinarith [hbnd]
        by_cases hden : 82944 < (82944 - 81770) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd3 hd5
          have hch4_37 : ¬ (37:ℕ) ∣ (p5 - 1) :=
            hchain 37 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 37 142).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((82944 - 81770) * v - 82944) ∣ (82944 * v - 82944 + 2) ∧
                Nat.Prime ((82944 * v - 82944 + 2) / ((82944 - 81770) * v - 82944)) ∧
                v < (82944 * v - 82944 + 2) / ((82944 - 81770) * v - 82944)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_17, hch4_37, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 37 142).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((82944 - 81770) * v - 82944) ∣ (82944 * v - 82944 + 2) ∧
                Nat.Prime ((82944 * v - 82944 + 2) / ((82944 - 81770) * v - 82944)) ∧
                v < (82944 * v - 82944 + 2) / ((82944 - 81770) * v - 82944))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 43
        have heq4 : 96768 * ((p5 - 1) * (p6 - 1))
            = 95030 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 112 := by nlinarith [hbnd]
        by_cases hden : 96768 < (96768 - 95030) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd3 hd5
          have hch4_43 : ¬ (43:ℕ) ∣ (p5 - 1) :=
            hchain 43 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 43 112).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((96768 - 95030) * v - 96768) ∣ (96768 * v - 96768 + 2) ∧
                Nat.Prime ((96768 * v - 96768 + 2) / ((96768 - 95030) * v - 96768)) ∧
                v < (96768 * v - 96768 + 2) / ((96768 - 95030) * v - 96768)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_17, hch4_43, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 43 112).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((96768 - 95030) * v - 96768) ∣ (96768 * v - 96768 + 2) ∧
                Nat.Prime ((96768 * v - 96768 + 2) / ((96768 - 95030) * v - 96768)) ∧
                v < (96768 * v - 96768 + 2) / ((96768 - 95030) * v - 96768))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 47
        have heq4 : 105984 * ((p5 - 1) * (p6 - 1))
            = 103870 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 101 := by nlinarith [hbnd]
        by_cases hden : 105984 < (105984 - 103870) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd3 hd5
          have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
            hchain 47 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 47 101).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 47 ∣ (v - 1) ∧
                ((105984 - 103870) * v - 105984) ∣ (105984 * v - 105984 + 2) ∧
                Nat.Prime ((105984 * v - 105984 + 2) / ((105984 - 103870) * v - 105984)) ∧
                v < (105984 * v - 105984 + 2) / ((105984 - 103870) * v - 105984)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_17, hch4_47, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 47 101).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 47 ∣ (v - 1) ∧
                ((105984 - 103870) * v - 105984) ∣ (105984 * v - 105984 + 2) ∧
                Nat.Prime ((105984 * v - 105984 + 2) / ((105984 - 103870) * v - 105984)) ∧
                v < (105984 * v - 105984 + 2) / ((105984 - 103870) * v - 105984))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 59
        have heq4 : 133632 * ((p5 - 1) * (p6 - 1))
            = 130390 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 83 := by nlinarith [hbnd]
        by_cases hden : 133632 < (133632 - 130390) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd3 hd5
          have hch4_59 : ¬ (59:ℕ) ∣ (p5 - 1) :=
            hchain 59 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 59 83).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 59 ∣ (v - 1) ∧
                ((133632 - 130390) * v - 133632) ∣ (133632 * v - 133632 + 2) ∧
                Nat.Prime ((133632 * v - 133632 + 2) / ((133632 - 130390) * v - 133632)) ∧
                v < (133632 * v - 133632 + 2) / ((133632 - 130390) * v - 133632)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_17, hch4_59, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 59 83).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 59 ∣ (v - 1) ∧
                ((133632 - 130390) * v - 133632) ∣ (133632 * v - 133632 + 2) ∧
                Nat.Prime ((133632 * v - 133632 + 2) / ((133632 - 130390) * v - 133632)) ∧
                v < (133632 * v - 133632 + 2) / ((133632 - 130390) * v - 133632))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 67
        have heq4 : 152064 * ((p5 - 1) * (p6 - 1))
            = 148070 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 77 := by nlinarith [hbnd]
        by_cases hden : 152064 < (152064 - 148070) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd3 hd5
          have hch4_67 : ¬ (67:ℕ) ∣ (p5 - 1) :=
            hchain 67 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 67 77).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 67 ∣ (v - 1) ∧
                ((152064 - 148070) * v - 152064) ∣ (152064 * v - 152064 + 2) ∧
                Nat.Prime ((152064 * v - 152064 + 2) / ((152064 - 148070) * v - 152064)) ∧
                v < (152064 * v - 152064 + 2) / ((152064 - 148070) * v - 152064)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_17, hch4_67, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 67 77).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 67 ∣ (v - 1) ∧
                ((152064 - 148070) * v - 152064) ∣ (152064 * v - 152064 + 2) ∧
                Nat.Prime ((152064 * v - 152064 + 2) / ((152064 - 148070) * v - 152064)) ∧
                v < (152064 * v - 152064 + 2) / ((152064 - 148070) * v - 152064))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
    · -- p3 = 19
      have heq3 : 2592 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 2470 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 67 := by
        by_contra hge
        exact cap_kill_3 (c := 67) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
        hchain 13 p4 (by norm_num) hp4 hd2 hd4
      have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
        hchain 19 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 19 67).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_13, hch3_19⟩
      have hset3 : (Finset.Ioo 19 67).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
          = ({23, 29, 37, 43, 47, 59} : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      fin_cases hmem3
      · -- p4 = 23
        have heq4 : 57024 * ((p5 - 1) * (p6 - 1))
            = 56810 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 534 := by nlinarith [hbnd]
        by_cases hden : 57024 < (57024 - 56810) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
            hchain 23 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 23 534).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((57024 - 56810) * v - 57024) ∣ (57024 * v - 57024 + 2) ∧
                Nat.Prime ((57024 * v - 57024 + 2) / ((57024 - 56810) * v - 57024)) ∧
                v < (57024 * v - 57024 + 2) / ((57024 - 56810) * v - 57024)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_19, hch4_23, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 23 534).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((57024 - 56810) * v - 57024) ∣ (57024 * v - 57024 + 2) ∧
                Nat.Prime ((57024 * v - 57024 + 2) / ((57024 - 56810) * v - 57024)) ∧
                v < (57024 * v - 57024 + 2) / ((57024 - 56810) * v - 57024))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 29
        have heq4 : 72576 * ((p5 - 1) * (p6 - 1))
            = 71630 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 154 := by nlinarith [hbnd]
        by_cases hden : 72576 < (72576 - 71630) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_29 : ¬ (29:ℕ) ∣ (p5 - 1) :=
            hchain 29 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 29 154).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((72576 - 71630) * v - 72576) ∣ (72576 * v - 72576 + 2) ∧
                Nat.Prime ((72576 * v - 72576 + 2) / ((72576 - 71630) * v - 72576)) ∧
                v < (72576 * v - 72576 + 2) / ((72576 - 71630) * v - 72576)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_19, hch4_29, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 29 154).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((72576 - 71630) * v - 72576) ∣ (72576 * v - 72576 + 2) ∧
                Nat.Prime ((72576 * v - 72576 + 2) / ((72576 - 71630) * v - 72576)) ∧
                v < (72576 * v - 72576 + 2) / ((72576 - 71630) * v - 72576))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 37
        have heq4 : 93312 * ((p5 - 1) * (p6 - 1))
            = 91390 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 98 := by nlinarith [hbnd]
        by_cases hden : 93312 < (93312 - 91390) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_37 : ¬ (37:ℕ) ∣ (p5 - 1) :=
            hchain 37 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 37 98).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((93312 - 91390) * v - 93312) ∣ (93312 * v - 93312 + 2) ∧
                Nat.Prime ((93312 * v - 93312 + 2) / ((93312 - 91390) * v - 93312)) ∧
                v < (93312 * v - 93312 + 2) / ((93312 - 91390) * v - 93312)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_19, hch4_37, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 37 98).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((93312 - 91390) * v - 93312) ∣ (93312 * v - 93312 + 2) ∧
                Nat.Prime ((93312 * v - 93312 + 2) / ((93312 - 91390) * v - 93312)) ∧
                v < (93312 * v - 93312 + 2) / ((93312 - 91390) * v - 93312))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 43
        have heq4 : 108864 * ((p5 - 1) * (p6 - 1))
            = 106210 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 83 := by nlinarith [hbnd]
        by_cases hden : 108864 < (108864 - 106210) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_43 : ¬ (43:ℕ) ∣ (p5 - 1) :=
            hchain 43 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 43 83).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((108864 - 106210) * v - 108864) ∣ (108864 * v - 108864 + 2) ∧
                Nat.Prime ((108864 * v - 108864 + 2) / ((108864 - 106210) * v - 108864)) ∧
                v < (108864 * v - 108864 + 2) / ((108864 - 106210) * v - 108864)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_19, hch4_43, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 43 83).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((108864 - 106210) * v - 108864) ∣ (108864 * v - 108864 + 2) ∧
                Nat.Prime ((108864 * v - 108864 + 2) / ((108864 - 106210) * v - 108864)) ∧
                v < (108864 * v - 108864 + 2) / ((108864 - 106210) * v - 108864))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 47
        have heq4 : 119232 * ((p5 - 1) * (p6 - 1))
            = 116090 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 77 := by nlinarith [hbnd]
        by_cases hden : 119232 < (119232 - 116090) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_47 : ¬ (47:ℕ) ∣ (p5 - 1) :=
            hchain 47 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 47 77).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 47 ∣ (v - 1) ∧
                ((119232 - 116090) * v - 119232) ∣ (119232 * v - 119232 + 2) ∧
                Nat.Prime ((119232 * v - 119232 + 2) / ((119232 - 116090) * v - 119232)) ∧
                v < (119232 * v - 119232 + 2) / ((119232 - 116090) * v - 119232)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_19, hch4_47, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 47 77).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 47 ∣ (v - 1) ∧
                ((119232 - 116090) * v - 119232) ∣ (119232 * v - 119232 + 2) ∧
                Nat.Prime ((119232 * v - 119232 + 2) / ((119232 - 116090) * v - 119232)) ∧
                v < (119232 * v - 119232 + 2) / ((119232 - 116090) * v - 119232))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 59
        have heq4 : 150336 * ((p5 - 1) * (p6 - 1))
            = 145730 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 66 := by nlinarith [hbnd]
        by_cases hden : 150336 < (150336 - 145730) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_59 : ¬ (59:ℕ) ∣ (p5 - 1) :=
            hchain 59 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 59 66).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 59 ∣ (v - 1) ∧
                ((150336 - 145730) * v - 150336) ∣ (150336 * v - 150336 + 2) ∧
                Nat.Prime ((150336 * v - 150336 + 2) / ((150336 - 145730) * v - 150336)) ∧
                v < (150336 * v - 150336 + 2) / ((150336 - 145730) * v - 150336)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_19, hch4_59, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 59 66).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 59 ∣ (v - 1) ∧
                ((150336 - 145730) * v - 150336) ∣ (150336 * v - 150336 + 2) ∧
                Nat.Prime ((150336 * v - 150336 + 2) / ((150336 - 145730) * v - 150336)) ∧
                v < (150336 * v - 150336 + 2) / ((150336 - 145730) * v - 150336))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
    · -- p3 = 23
      have heq3 : 3168 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 2990 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 53 := by
        by_contra hge
        exact cap_kill_3 (c := 53) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
        hchain 13 p4 (by norm_num) hp4 hd2 hd4
      have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
        hchain 23 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 23 53).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_13, hch3_23⟩
      have hset3 : (Finset.Ioo 23 53).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1))
          = ({29, 37, 43} : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      fin_cases hmem3
      · -- p4 = 29
        have heq4 : 88704 * ((p5 - 1) * (p6 - 1))
            = 86710 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 90 := by nlinarith [hbnd]
        by_cases hden : 88704 < (88704 - 86710) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
            hchain 23 p5 (by norm_num) hp5 hd3 hd5
          have hch4_29 : ¬ (29:ℕ) ∣ (p5 - 1) :=
            hchain 29 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 29 90).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((88704 - 86710) * v - 88704) ∣ (88704 * v - 88704 + 2) ∧
                Nat.Prime ((88704 * v - 88704 + 2) / ((88704 - 86710) * v - 88704)) ∧
                v < (88704 * v - 88704 + 2) / ((88704 - 86710) * v - 88704)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_23, hch4_29, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 29 90).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((88704 - 86710) * v - 88704) ∣ (88704 * v - 88704 + 2) ∧
                Nat.Prime ((88704 * v - 88704 + 2) / ((88704 - 86710) * v - 88704)) ∧
                v < (88704 * v - 88704 + 2) / ((88704 - 86710) * v - 88704))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 37
        have heq4 : 114048 * ((p5 - 1) * (p6 - 1))
            = 110630 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 68 := by nlinarith [hbnd]
        by_cases hden : 114048 < (114048 - 110630) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
            hchain 23 p5 (by norm_num) hp5 hd3 hd5
          have hch4_37 : ¬ (37:ℕ) ∣ (p5 - 1) :=
            hchain 37 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 37 68).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((114048 - 110630) * v - 114048) ∣ (114048 * v - 114048 + 2) ∧
                Nat.Prime ((114048 * v - 114048 + 2) / ((114048 - 110630) * v - 114048)) ∧
                v < (114048 * v - 114048 + 2) / ((114048 - 110630) * v - 114048)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_23, hch4_37, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 37 68).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((114048 - 110630) * v - 114048) ∣ (114048 * v - 114048 + 2) ∧
                Nat.Prime ((114048 * v - 114048 + 2) / ((114048 - 110630) * v - 114048)) ∧
                v < (114048 * v - 114048 + 2) / ((114048 - 110630) * v - 114048))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 43
        have heq4 : 133056 * ((p5 - 1) * (p6 - 1))
            = 128570 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 60 := by nlinarith [hbnd]
        by_cases hden : 133056 < (133056 - 128570) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
            hchain 23 p5 (by norm_num) hp5 hd3 hd5
          have hch4_43 : ¬ (43:ℕ) ∣ (p5 - 1) :=
            hchain 43 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 43 60).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((133056 - 128570) * v - 133056) ∣ (133056 * v - 133056 + 2) ∧
                Nat.Prime ((133056 * v - 133056 + 2) / ((133056 - 128570) * v - 133056)) ∧
                v < (133056 * v - 133056 + 2) / ((133056 - 128570) * v - 133056)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_23, hch4_43, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 43 60).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((133056 - 128570) * v - 133056) ∣ (133056 * v - 133056 + 2) ∧
                Nat.Prime ((133056 * v - 133056 + 2) / ((133056 - 128570) * v - 133056)) ∧
                v < (133056 * v - 133056 + 2) / ((133056 - 128570) * v - 133056))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
    · -- p3 = 29
      have heq3 : 4032 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 3770 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 47 := by
        by_contra hge
        exact cap_kill_3 (c := 47) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
        hchain 13 p4 (by norm_num) hp4 hd2 hd4
      have hch3_29 : ¬ (29:ℕ) ∣ (p4 - 1) :=
        hchain 29 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 29 47).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 29 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_13, hch3_29⟩
      have hset3 : (Finset.Ioo 29 47).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 29 ∣ (v - 1))
          = ({37, 43} : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      fin_cases hmem3
      · -- p4 = 37
        have heq4 : 145152 * ((p5 - 1) * (p6 - 1))
            = 139490 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 52 := by nlinarith [hbnd]
        by_cases hden : 145152 < (145152 - 139490) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_29 : ¬ (29:ℕ) ∣ (p5 - 1) :=
            hchain 29 p5 (by norm_num) hp5 hd3 hd5
          have hch4_37 : ¬ (37:ℕ) ∣ (p5 - 1) :=
            hchain 37 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 37 52).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((145152 - 139490) * v - 145152) ∣ (145152 * v - 145152 + 2) ∧
                Nat.Prime ((145152 * v - 145152 + 2) / ((145152 - 139490) * v - 145152)) ∧
                v < (145152 * v - 145152 + 2) / ((145152 - 139490) * v - 145152)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_29, hch4_37, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 37 52).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((145152 - 139490) * v - 145152) ∣ (145152 * v - 145152 + 2) ∧
                Nat.Prime ((145152 * v - 145152 + 2) / ((145152 - 139490) * v - 145152)) ∧
                v < (145152 * v - 145152 + 2) / ((145152 - 139490) * v - 145152))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 43
        have heq4 : 169344 * ((p5 - 1) * (p6 - 1))
            = 162110 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 48 := by nlinarith [hbnd]
        by_cases hden : 169344 < (169344 - 162110) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
            hchain 13 p5 (by norm_num) hp5 hd2 hd5
          have hch4_29 : ¬ (29:ℕ) ∣ (p5 - 1) :=
            hchain 29 p5 (by norm_num) hp5 hd3 hd5
          have hch4_43 : ¬ (43:ℕ) ∣ (p5 - 1) :=
            hchain 43 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 43 48).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((169344 - 162110) * v - 169344) ∣ (169344 * v - 169344 + 2) ∧
                Nat.Prime ((169344 * v - 169344 + 2) / ((169344 - 162110) * v - 169344)) ∧
                v < (169344 * v - 169344 + 2) / ((169344 - 162110) * v - 169344)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_13, hch4_29, hch4_43, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 43 48).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((169344 - 162110) * v - 169344) ∣ (169344 * v - 169344 + 2) ∧
                Nat.Prime ((169344 * v - 169344 + 2) / ((169344 - 162110) * v - 169344)) ∧
                v < (169344 * v - 169344 + 2) / ((169344 - 162110) * v - 169344))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
    · -- p3 = 37
      have heq3 : 5184 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 4810 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 41 := by
        by_contra hge
        exact cap_kill_3 (c := 41) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
        hchain 13 p4 (by norm_num) hp4 hd2 hd4
      have hch3_37 : ¬ (37:ℕ) ∣ (p4 - 1) :=
        hchain 37 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 37 41).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 37 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_13, hch3_37⟩
      have hset3 : (Finset.Ioo 37 41).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 37 ∣ (v - 1))
          = (∅ : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      simp at hmem3
  · -- p2 = 17
    have heq2 : 192 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
        = 170 * (p3 * (p4 * (p5 * p6))) + 2 := by
      ring_nf at heq1 ⊢
      omega
    have hcap2 : p3 < 37 := by
      by_contra hge
      exact cap_kill_4 (c := 37) (by norm_num) (by norm_num) (by omega)
        h3.le h4.le h5.le heq2
    have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
      hchain 5 p3 (by norm_num) hp3 hd1 hd3
    have hch2_17 : ¬ (17:ℕ) ∣ (p3 - 1) :=
      hchain 17 p3 (by norm_num) hp3 hd2 hd3
    have hmem2 : p3 ∈ (Finset.Ioo 17 37).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_17⟩
    have hset2 : (Finset.Ioo 17 37).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1))
        = ({19, 23, 29} : Finset ℕ) := by native_decide
    rw [hset2] at hmem2
    fin_cases hmem2
    · -- p3 = 19
      have heq3 : 3456 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 3230 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 47 := by
        by_contra hge
        exact cap_kill_3 (c := 47) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
        hchain 17 p4 (by norm_num) hp4 hd2 hd4
      have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
        hchain 19 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 19 47).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_17, hch3_19⟩
      have hset3 : (Finset.Ioo 19 47).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
          = ({23, 29, 37, 43} : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      fin_cases hmem3
      · -- p4 = 23
        have heq4 : 76032 * ((p5 - 1) * (p6 - 1))
            = 74290 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 88 := by nlinarith [hbnd]
        by_cases hden : 76032 < (76032 - 74290) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
            hchain 23 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 23 88).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((76032 - 74290) * v - 76032) ∣ (76032 * v - 76032 + 2) ∧
                Nat.Prime ((76032 * v - 76032 + 2) / ((76032 - 74290) * v - 76032)) ∧
                v < (76032 * v - 76032 + 2) / ((76032 - 74290) * v - 76032)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_17, hch4_19, hch4_23, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 23 88).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((76032 - 74290) * v - 76032) ∣ (76032 * v - 76032 + 2) ∧
                Nat.Prime ((76032 * v - 76032 + 2) / ((76032 - 74290) * v - 76032)) ∧
                v < (76032 * v - 76032 + 2) / ((76032 - 74290) * v - 76032))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 29
        have heq4 : 96768 * ((p5 - 1) * (p6 - 1))
            = 93670 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 63 := by nlinarith [hbnd]
        by_cases hden : 96768 < (96768 - 93670) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_29 : ¬ (29:ℕ) ∣ (p5 - 1) :=
            hchain 29 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 29 63).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((96768 - 93670) * v - 96768) ∣ (96768 * v - 96768 + 2) ∧
                Nat.Prime ((96768 * v - 96768 + 2) / ((96768 - 93670) * v - 96768)) ∧
                v < (96768 * v - 96768 + 2) / ((96768 - 93670) * v - 96768)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_17, hch4_19, hch4_29, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 29 63).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((96768 - 93670) * v - 96768) ∣ (96768 * v - 96768 + 2) ∧
                Nat.Prime ((96768 * v - 96768 + 2) / ((96768 - 93670) * v - 96768)) ∧
                v < (96768 * v - 96768 + 2) / ((96768 - 93670) * v - 96768))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 37
        have heq4 : 124416 * ((p5 - 1) * (p6 - 1))
            = 119510 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 52 := by nlinarith [hbnd]
        by_cases hden : 124416 < (124416 - 119510) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_37 : ¬ (37:ℕ) ∣ (p5 - 1) :=
            hchain 37 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 37 52).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((124416 - 119510) * v - 124416) ∣ (124416 * v - 124416 + 2) ∧
                Nat.Prime ((124416 * v - 124416 + 2) / ((124416 - 119510) * v - 124416)) ∧
                v < (124416 * v - 124416 + 2) / ((124416 - 119510) * v - 124416)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_17, hch4_19, hch4_37, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 37 52).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((124416 - 119510) * v - 124416) ∣ (124416 * v - 124416 + 2) ∧
                Nat.Prime ((124416 * v - 124416 + 2) / ((124416 - 119510) * v - 124416)) ∧
                v < (124416 * v - 124416 + 2) / ((124416 - 119510) * v - 124416))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 43
        have heq4 : 145152 * ((p5 - 1) * (p6 - 1))
            = 138890 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 47 := by nlinarith [hbnd]
        by_cases hden : 145152 < (145152 - 138890) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd2 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd3 hd5
          have hch4_43 : ¬ (43:ℕ) ∣ (p5 - 1) :=
            hchain 43 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 43 47).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((145152 - 138890) * v - 145152) ∣ (145152 * v - 145152 + 2) ∧
                Nat.Prime ((145152 * v - 145152 + 2) / ((145152 - 138890) * v - 145152)) ∧
                v < (145152 * v - 145152 + 2) / ((145152 - 138890) * v - 145152)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_17, hch4_19, hch4_43, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 43 47).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 43 ∣ (v - 1) ∧
                ((145152 - 138890) * v - 145152) ∣ (145152 * v - 145152 + 2) ∧
                Nat.Prime ((145152 * v - 145152 + 2) / ((145152 - 138890) * v - 145152)) ∧
                v < (145152 * v - 145152 + 2) / ((145152 - 138890) * v - 145152))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
    · -- p3 = 23
      have heq3 : 4224 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 3910 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 41 := by
        by_contra hge
        exact cap_kill_3 (c := 41) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
        hchain 17 p4 (by norm_num) hp4 hd2 hd4
      have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
        hchain 23 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 23 41).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_17, hch3_23⟩
      have hset3 : (Finset.Ioo 23 41).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1))
          = ({29, 37} : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      fin_cases hmem3
      · -- p4 = 29
        have heq4 : 118272 * ((p5 - 1) * (p6 - 1))
            = 113390 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 49 := by nlinarith [hbnd]
        by_cases hden : 118272 < (118272 - 113390) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd2 hd5
          have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
            hchain 23 p5 (by norm_num) hp5 hd3 hd5
          have hch4_29 : ¬ (29:ℕ) ∣ (p5 - 1) :=
            hchain 29 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 29 49).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((118272 - 113390) * v - 118272) ∣ (118272 * v - 118272 + 2) ∧
                Nat.Prime ((118272 * v - 118272 + 2) / ((118272 - 113390) * v - 118272)) ∧
                v < (118272 * v - 118272 + 2) / ((118272 - 113390) * v - 118272)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_17, hch4_23, hch4_29, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 29 49).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((118272 - 113390) * v - 118272) ∣ (118272 * v - 118272 + 2) ∧
                Nat.Prime ((118272 * v - 118272 + 2) / ((118272 - 113390) * v - 118272)) ∧
                v < (118272 * v - 118272 + 2) / ((118272 - 113390) * v - 118272))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p4 = 37
        have heq4 : 152064 * ((p5 - 1) * (p6 - 1))
            = 144670 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 42 := by nlinarith [hbnd]
        by_cases hden : 152064 < (152064 - 144670) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
            hchain 17 p5 (by norm_num) hp5 hd2 hd5
          have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
            hchain 23 p5 (by norm_num) hp5 hd3 hd5
          have hch4_37 : ¬ (37:ℕ) ∣ (p5 - 1) :=
            hchain 37 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 37 42).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((152064 - 144670) * v - 152064) ∣ (152064 * v - 152064 + 2) ∧
                Nat.Prime ((152064 * v - 152064 + 2) / ((152064 - 144670) * v - 152064)) ∧
                v < (152064 * v - 152064 + 2) / ((152064 - 144670) * v - 152064)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_17, hch4_23, hch4_37, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 37 42).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((152064 - 144670) * v - 152064) ∣ (152064 * v - 152064 + 2) ∧
                Nat.Prime ((152064 * v - 152064 + 2) / ((152064 - 144670) * v - 152064)) ∧
                v < (152064 * v - 152064 + 2) / ((152064 - 144670) * v - 152064))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
    · -- p3 = 29
      have heq3 : 5376 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 4930 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 37 := by
        by_contra hge
        exact cap_kill_3 (c := 37) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
        hchain 17 p4 (by norm_num) hp4 hd2 hd4
      have hch3_29 : ¬ (29:ℕ) ∣ (p4 - 1) :=
        hchain 29 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 29 37).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1) ∧ ¬ 29 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_17, hch3_29⟩
      have hset3 : (Finset.Ioo 29 37).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1) ∧ ¬ 29 ∣ (v - 1))
          = (∅ : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      simp at hmem3
  · -- p2 = 19
    have heq2 : 216 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
        = 190 * (p3 * (p4 * (p5 * p6))) + 2 := by
      ring_nf at heq1 ⊢
      omega
    have hcap2 : p3 < 37 := by
      by_contra hge
      exact cap_kill_4 (c := 37) (by norm_num) (by norm_num) (by omega)
        h3.le h4.le h5.le heq2
    have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
      hchain 5 p3 (by norm_num) hp3 hd1 hd3
    have hch2_19 : ¬ (19:ℕ) ∣ (p3 - 1) :=
      hchain 19 p3 (by norm_num) hp3 hd2 hd3
    have hmem2 : p3 ∈ (Finset.Ioo 19 37).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_19⟩
    have hset2 : (Finset.Ioo 19 37).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
        = ({23, 29} : Finset ℕ) := by native_decide
    rw [hset2] at hmem2
    fin_cases hmem2
    · -- p3 = 23
      have heq3 : 4752 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 4370 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 37 := by
        by_contra hge
        exact cap_kill_3 (c := 37) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
        hchain 19 p4 (by norm_num) hp4 hd2 hd4
      have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
        hchain 23 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 23 37).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_19, hch3_23⟩
      have hset3 : (Finset.Ioo 23 37).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1))
          = ({29} : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      fin_cases hmem3
      · -- p4 = 29
        have heq4 : 133056 * ((p5 - 1) * (p6 - 1))
            = 126730 * (p5 * p6) + 2 := by
          ring_nf at heq3 ⊢
          omega
        have hs2 : 2 ≤ p5 := by omega
        have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
        have hshi : p5 ≤ 43 := by nlinarith [hbnd]
        by_cases hden : 133056 < (133056 - 126730) * p5
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
          have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
            hchain 5 p5 (by norm_num) hp5 hd1 hd5
          have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
            hchain 19 p5 (by norm_num) hp5 hd2 hd5
          have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
            hchain 23 p5 (by norm_num) hp5 hd3 hd5
          have hch4_29 : ¬ (29:ℕ) ∣ (p5 - 1) :=
            hchain 29 p5 (by norm_num) hp5 hd4 hd5
          have hmem4 : p5 ∈ (Finset.Ioc 29 43).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((133056 - 126730) * v - 133056) ∣ (133056 * v - 133056 + 2) ∧
                Nat.Prime ((133056 * v - 133056 + 2) / ((133056 - 126730) * v - 133056)) ∧
                v < (133056 * v - 133056 + 2) / ((133056 - 126730) * v - 133056)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp5, hch4_5, hch4_19, hch4_23, hch4_29, hdvd,
              by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
          have hempty : (Finset.Ioc 29 43).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((133056 - 126730) * v - 133056) ∣ (133056 * v - 133056 + 2) ∧
                Nat.Prime ((133056 * v - 133056 + 2) / ((133056 - 126730) * v - 133056)) ∧
                v < (133056 * v - 133056 + 2) / ((133056 - 126730) * v - 133056))
              = ∅ := by native_decide
          rw [hempty] at hmem4
          simp at hmem4
        · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
    · -- p3 = 29
      have heq3 : 6048 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 5510 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 37 := by
        by_contra hge
        exact cap_kill_3 (c := 37) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
        hchain 19 p4 (by norm_num) hp4 hd2 hd4
      have hch3_29 : ¬ (29:ℕ) ∣ (p4 - 1) :=
        hchain 29 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 29 37).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1) ∧ ¬ 29 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_19, hch3_29⟩
      have hset3 : (Finset.Ioo 29 37).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1) ∧ ¬ 29 ∣ (v - 1))
          = (∅ : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      simp at hmem3
  · -- p2 = 23
    have heq2 : 264 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
        = 230 * (p3 * (p4 * (p5 * p6))) + 2 := by
      ring_nf at heq1 ⊢
      omega
    have hcap2 : p3 < 31 := by
      by_contra hge
      exact cap_kill_4 (c := 31) (by norm_num) (by norm_num) (by omega)
        h3.le h4.le h5.le heq2
    have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
      hchain 5 p3 (by norm_num) hp3 hd1 hd3
    have hch2_23 : ¬ (23:ℕ) ∣ (p3 - 1) :=
      hchain 23 p3 (by norm_num) hp3 hd2 hd3
    have hmem2 : p3 ∈ (Finset.Ioo 23 31).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_23⟩
    have hset2 : (Finset.Ioo 23 31).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1))
        = ({29} : Finset ℕ) := by native_decide
    rw [hset2] at hmem2
    fin_cases hmem2
    · -- p3 = 29
      have heq3 : 7392 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
          = 6670 * (p4 * (p5 * p6)) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hcap3 : p4 < 31 := by
        by_contra hge
        exact cap_kill_3 (c := 31) (by norm_num) (by norm_num) (by omega)
          h4.le h5.le heq3
      have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
        hchain 5 p4 (by norm_num) hp4 hd1 hd4
      have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
        hchain 23 p4 (by norm_num) hp4 hd2 hd4
      have hch3_29 : ¬ (29:ℕ) ∣ (p4 - 1) :=
        hchain 29 p4 (by norm_num) hp4 hd3 hd4
      have hmem3 : p4 ∈ (Finset.Ioo 29 31).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1) ∧ ¬ 29 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_23, hch3_29⟩
      have hset3 : (Finset.Ioo 29 31).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1) ∧ ¬ 29 ∣ (v - 1))
          = (∅ : Finset ℕ) := by native_decide
      rw [hset3] at hmem3
      simp at hmem3

end EG411Structure