-- AUTO-GENERATED by oracle/data_engine/omega_ladder/codegen.py from a certified omega-tree JSON.
-- Certified kill-tree for omega = 5: 3*phi(n) = 2n+2 has NO solution with 5 distinct prime factors.
import SolutionStructure
import OmegaTreeSupport

namespace EG411Structure

set_option linter.style.nativeDecide false

set_option maxRecDepth 8000 in
set_option maxHeartbeats 0 in
theorem omega5_empty (n : ℕ) (hn : 3 * Nat.totient n = 2 * n + 2)
    (p1 p2 p3 p4 p5 : ℕ) (hp1 : p1.Prime) (hp2 : p2.Prime) (hp3 : p3.Prime) (hp4 : p4.Prime) (hp5 : p5.Prime)
    (h1 : p1 < p2) (h2 : p2 < p3) (h3 : p3 < p4) (h4 : p4 < p5)
    (hN : n = p1 * (p2 * (p3 * (p4 * p5)))) : False := by
  have hN' : n = p1 * (p2 * (p3 * (p4 * p5))) := hN
  have hd1 : p1 ∣ n := ⟨p2 * (p3 * (p4 * p5)), hN'⟩
  have hd2 : p2 ∣ n := ⟨p1 * (p3 * (p4 * p5)), by rw [hN']; ring⟩
  have hd3 : p3 ∣ n := ⟨p1 * (p2 * (p4 * p5)), by rw [hN']; ring⟩
  have hd4 : p4 ∣ n := ⟨p1 * (p2 * (p3 * p5)), by rw [hN']; ring⟩
  have hge5 : 5 ≤ p1 := solution_min_prime_ge_five hn p1 hp1 hd1
  have hchain := solution_no_prime_chain hn
  have heq0 : 3 * ((p1 - 1) * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))))
      = 2 * (p1 * (p2 * (p3 * (p4 * p5)))) + 2 := by
    have h := hn
    rw [hN', phi_prod_5 hp1 hp2 hp3 hp4 hp5 h1 h2 h3 h4] at h
    exact h
  have hcap0 : p1 < 13 := by
    by_contra hge
    exact cap_kill_5 (c := 13) (by norm_num) (by norm_num) (by omega)
      h1.le h2.le h3.le h4.le heq0
  have hmem0 : p1 ∈ (Finset.Ioo 4 13).filter
      (fun v => Nat.Prime v) :=
    Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap0⟩, hp1⟩
  have hset0 : (Finset.Ioo 4 13).filter
      (fun v => Nat.Prime v)
      = ({5, 7, 11} : Finset ℕ) := by native_decide
  rw [hset0] at hmem0
  fin_cases hmem0
  · -- p1 = 5
    have heq1 : 12 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * (p5 - 1))))
        = 10 * (p2 * (p3 * (p4 * p5))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : p2 < 23 := by
      by_contra hge
      exact cap_kill_4 (c := 23) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le heq1
    have hch1_5 : ¬ (5:ℕ) ∣ (p2 - 1) :=
      hchain 5 p2 (by norm_num) hp2 hd1 hd2
    have hmem1 : p2 ∈ (Finset.Ioo 5 23).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_5⟩
    have hset1 : (Finset.Ioo 5 23).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1))
        = ({7, 13, 17, 19} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- p2 = 7
      have heq2 : 72 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 70 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 107 := by
        by_contra hge
        exact cap_kill_3 (c := 107) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
        hchain 5 p3 (by norm_num) hp3 hd1 hd3
      have hch2_7 : ¬ (7:ℕ) ∣ (p3 - 1) :=
        hchain 7 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 7 107).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 7 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_7⟩
      have hset2 : (Finset.Ioo 7 107).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 7 ∣ (v - 1))
          = ({13, 17, 19, 23, 37, 47, 53, 59,
              67, 73, 79, 83, 89, 97, 103} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 13
        have heq3 : 864 * ((p4 - 1) * (p5 - 1))
            = 910 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq3
      · -- p3 = 17
        have heq3 : 1152 * ((p4 - 1) * (p5 - 1))
            = 1190 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq3
      · -- p3 = 19
        have heq3 : 1296 * ((p4 - 1) * (p5 - 1))
            = 1330 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq3
      · -- p3 = 23
        have heq3 : 1584 * ((p4 - 1) * (p5 - 1))
            = 1610 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq3
      · -- p3 = 37
        have heq3 : 2592 * ((p4 - 1) * (p5 - 1))
            = 2590 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 2593 := by nlinarith [hbnd]
        by_cases hden : 2592 < (2592 - 2590) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_37 : ¬ (37:ℕ) ∣ (p4 - 1) :=
            hchain 37 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 37 2593).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((2592 - 2590) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
                Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2590) * v - 2592)) ∧
                v < (2592 * v - 2592 + 2) / ((2592 - 2590) * v - 2592)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_37, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 37 2593).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((2592 - 2590) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
                Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2590) * v - 2592)) ∧
                v < (2592 * v - 2592 + 2) / ((2592 - 2590) * v - 2592))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 47
        have heq3 : 3312 * ((p4 - 1) * (p5 - 1))
            = 3290 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 302 := by nlinarith [hbnd]
        by_cases hden : 3312 < (3312 - 3290) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_47 : ¬ (47:ℕ) ∣ (p4 - 1) :=
            hchain 47 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 47 302).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 47 ∣ (v - 1) ∧
                ((3312 - 3290) * v - 3312) ∣ (3312 * v - 3312 + 2) ∧
                Nat.Prime ((3312 * v - 3312 + 2) / ((3312 - 3290) * v - 3312)) ∧
                v < (3312 * v - 3312 + 2) / ((3312 - 3290) * v - 3312)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_47, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 47 302).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 47 ∣ (v - 1) ∧
                ((3312 - 3290) * v - 3312) ∣ (3312 * v - 3312 + 2) ∧
                Nat.Prime ((3312 * v - 3312 + 2) / ((3312 - 3290) * v - 3312)) ∧
                v < (3312 * v - 3312 + 2) / ((3312 - 3290) * v - 3312))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 53
        have heq3 : 3744 * ((p4 - 1) * (p5 - 1))
            = 3710 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 221 := by nlinarith [hbnd]
        by_cases hden : 3744 < (3744 - 3710) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_53 : ¬ (53:ℕ) ∣ (p4 - 1) :=
            hchain 53 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 53 221).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 53 ∣ (v - 1) ∧
                ((3744 - 3710) * v - 3744) ∣ (3744 * v - 3744 + 2) ∧
                Nat.Prime ((3744 * v - 3744 + 2) / ((3744 - 3710) * v - 3744)) ∧
                v < (3744 * v - 3744 + 2) / ((3744 - 3710) * v - 3744)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_53, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 53 221).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 53 ∣ (v - 1) ∧
                ((3744 - 3710) * v - 3744) ∣ (3744 * v - 3744 + 2) ∧
                Nat.Prime ((3744 * v - 3744 + 2) / ((3744 - 3710) * v - 3744)) ∧
                v < (3744 * v - 3744 + 2) / ((3744 - 3710) * v - 3744))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 59
        have heq3 : 4176 * ((p4 - 1) * (p5 - 1))
            = 4130 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 183 := by nlinarith [hbnd]
        by_cases hden : 4176 < (4176 - 4130) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_59 : ¬ (59:ℕ) ∣ (p4 - 1) :=
            hchain 59 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 59 183).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 59 ∣ (v - 1) ∧
                ((4176 - 4130) * v - 4176) ∣ (4176 * v - 4176 + 2) ∧
                Nat.Prime ((4176 * v - 4176 + 2) / ((4176 - 4130) * v - 4176)) ∧
                v < (4176 * v - 4176 + 2) / ((4176 - 4130) * v - 4176)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_59, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 59 183).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 59 ∣ (v - 1) ∧
                ((4176 - 4130) * v - 4176) ∣ (4176 * v - 4176 + 2) ∧
                Nat.Prime ((4176 * v - 4176 + 2) / ((4176 - 4130) * v - 4176)) ∧
                v < (4176 * v - 4176 + 2) / ((4176 - 4130) * v - 4176))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 67
        have heq3 : 4752 * ((p4 - 1) * (p5 - 1))
            = 4690 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 154 := by nlinarith [hbnd]
        by_cases hden : 4752 < (4752 - 4690) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_67 : ¬ (67:ℕ) ∣ (p4 - 1) :=
            hchain 67 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 67 154).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 67 ∣ (v - 1) ∧
                ((4752 - 4690) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
                Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4690) * v - 4752)) ∧
                v < (4752 * v - 4752 + 2) / ((4752 - 4690) * v - 4752)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_67, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 67 154).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 67 ∣ (v - 1) ∧
                ((4752 - 4690) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
                Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4690) * v - 4752)) ∧
                v < (4752 * v - 4752 + 2) / ((4752 - 4690) * v - 4752))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 73
        have heq3 : 5184 * ((p4 - 1) * (p5 - 1))
            = 5110 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 141 := by nlinarith [hbnd]
        by_cases hden : 5184 < (5184 - 5110) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_73 : ¬ (73:ℕ) ∣ (p4 - 1) :=
            hchain 73 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 73 141).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 73 ∣ (v - 1) ∧
                ((5184 - 5110) * v - 5184) ∣ (5184 * v - 5184 + 2) ∧
                Nat.Prime ((5184 * v - 5184 + 2) / ((5184 - 5110) * v - 5184)) ∧
                v < (5184 * v - 5184 + 2) / ((5184 - 5110) * v - 5184)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_73, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 73 141).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 73 ∣ (v - 1) ∧
                ((5184 - 5110) * v - 5184) ∣ (5184 * v - 5184 + 2) ∧
                Nat.Prime ((5184 * v - 5184 + 2) / ((5184 - 5110) * v - 5184)) ∧
                v < (5184 * v - 5184 + 2) / ((5184 - 5110) * v - 5184))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 79
        have heq3 : 5616 * ((p4 - 1) * (p5 - 1))
            = 5530 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 132 := by nlinarith [hbnd]
        by_cases hden : 5616 < (5616 - 5530) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_79 : ¬ (79:ℕ) ∣ (p4 - 1) :=
            hchain 79 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 79 132).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 79 ∣ (v - 1) ∧
                ((5616 - 5530) * v - 5616) ∣ (5616 * v - 5616 + 2) ∧
                Nat.Prime ((5616 * v - 5616 + 2) / ((5616 - 5530) * v - 5616)) ∧
                v < (5616 * v - 5616 + 2) / ((5616 - 5530) * v - 5616)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_79, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 79 132).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 79 ∣ (v - 1) ∧
                ((5616 - 5530) * v - 5616) ∣ (5616 * v - 5616 + 2) ∧
                Nat.Prime ((5616 * v - 5616 + 2) / ((5616 - 5530) * v - 5616)) ∧
                v < (5616 * v - 5616 + 2) / ((5616 - 5530) * v - 5616))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 83
        have heq3 : 5904 * ((p4 - 1) * (p5 - 1))
            = 5810 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 127 := by nlinarith [hbnd]
        by_cases hden : 5904 < (5904 - 5810) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_83 : ¬ (83:ℕ) ∣ (p4 - 1) :=
            hchain 83 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 83 127).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 83 ∣ (v - 1) ∧
                ((5904 - 5810) * v - 5904) ∣ (5904 * v - 5904 + 2) ∧
                Nat.Prime ((5904 * v - 5904 + 2) / ((5904 - 5810) * v - 5904)) ∧
                v < (5904 * v - 5904 + 2) / ((5904 - 5810) * v - 5904)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_83, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 83 127).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 83 ∣ (v - 1) ∧
                ((5904 - 5810) * v - 5904) ∣ (5904 * v - 5904 + 2) ∧
                Nat.Prime ((5904 * v - 5904 + 2) / ((5904 - 5810) * v - 5904)) ∧
                v < (5904 * v - 5904 + 2) / ((5904 - 5810) * v - 5904))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 89
        have heq3 : 6336 * ((p4 - 1) * (p5 - 1))
            = 6230 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 121 := by nlinarith [hbnd]
        by_cases hden : 6336 < (6336 - 6230) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_89 : ¬ (89:ℕ) ∣ (p4 - 1) :=
            hchain 89 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 89 121).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 89 ∣ (v - 1) ∧
                ((6336 - 6230) * v - 6336) ∣ (6336 * v - 6336 + 2) ∧
                Nat.Prime ((6336 * v - 6336 + 2) / ((6336 - 6230) * v - 6336)) ∧
                v < (6336 * v - 6336 + 2) / ((6336 - 6230) * v - 6336)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_89, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 89 121).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 89 ∣ (v - 1) ∧
                ((6336 - 6230) * v - 6336) ∣ (6336 * v - 6336 + 2) ∧
                Nat.Prime ((6336 * v - 6336 + 2) / ((6336 - 6230) * v - 6336)) ∧
                v < (6336 * v - 6336 + 2) / ((6336 - 6230) * v - 6336))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 97
        have heq3 : 6912 * ((p4 - 1) * (p5 - 1))
            = 6790 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 114 := by nlinarith [hbnd]
        by_cases hden : 6912 < (6912 - 6790) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_97 : ¬ (97:ℕ) ∣ (p4 - 1) :=
            hchain 97 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 97 114).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 97 ∣ (v - 1) ∧
                ((6912 - 6790) * v - 6912) ∣ (6912 * v - 6912 + 2) ∧
                Nat.Prime ((6912 * v - 6912 + 2) / ((6912 - 6790) * v - 6912)) ∧
                v < (6912 * v - 6912 + 2) / ((6912 - 6790) * v - 6912)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_97, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 97 114).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 97 ∣ (v - 1) ∧
                ((6912 - 6790) * v - 6912) ∣ (6912 * v - 6912 + 2) ∧
                Nat.Prime ((6912 * v - 6912 + 2) / ((6912 - 6790) * v - 6912)) ∧
                v < (6912 * v - 6912 + 2) / ((6912 - 6790) * v - 6912))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 103
        have heq3 : 7344 * ((p4 - 1) * (p5 - 1))
            = 7210 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 111 := by nlinarith [hbnd]
        by_cases hden : 7344 < (7344 - 7210) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd2 hd4
          have hch3_103 : ¬ (103:ℕ) ∣ (p4 - 1) :=
            hchain 103 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 103 111).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 103 ∣ (v - 1) ∧
                ((7344 - 7210) * v - 7344) ∣ (7344 * v - 7344 + 2) ∧
                Nat.Prime ((7344 * v - 7344 + 2) / ((7344 - 7210) * v - 7344)) ∧
                v < (7344 * v - 7344 + 2) / ((7344 - 7210) * v - 7344)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_7, hch3_103, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 103 111).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 103 ∣ (v - 1) ∧
                ((7344 - 7210) * v - 7344) ∣ (7344 * v - 7344 + 2) ∧
                Nat.Prime ((7344 * v - 7344 + 2) / ((7344 - 7210) * v - 7344)) ∧
                v < (7344 * v - 7344 + 2) / ((7344 - 7210) * v - 7344))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- p2 = 13
      have heq2 : 144 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 130 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 31 := by
        by_contra hge
        exact cap_kill_3 (c := 31) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
        hchain 5 p3 (by norm_num) hp3 hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (p3 - 1) :=
        hchain 13 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 13 31).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_13⟩
      have hset2 : (Finset.Ioo 13 31).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = ({17, 19, 23, 29} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 17
        have heq3 : 2304 * ((p4 - 1) * (p5 - 1))
            = 2210 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 50 := by nlinarith [hbnd]
        by_cases hden : 2304 < (2304 - 2210) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
            hchain 13 p4 (by norm_num) hp4 hd2 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
            hchain 17 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 17 50).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2304 - 2210) * v - 2304) ∣ (2304 * v - 2304 + 2) ∧
                Nat.Prime ((2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304)) ∧
                v < (2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_13, hch3_17, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 17 50).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2304 - 2210) * v - 2304) ∣ (2304 * v - 2304 + 2) ∧
                Nat.Prime ((2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304)) ∧
                v < (2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 19
        have heq3 : 2592 * ((p4 - 1) * (p5 - 1))
            = 2470 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 43 := by nlinarith [hbnd]
        by_cases hden : 2592 < (2592 - 2470) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
            hchain 13 p4 (by norm_num) hp4 hd2 hd4
          have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
            hchain 19 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 19 43).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((2592 - 2470) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
                Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592)) ∧
                v < (2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_13, hch3_19, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 19 43).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((2592 - 2470) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
                Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592)) ∧
                v < (2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 23
        have heq3 : 3168 * ((p4 - 1) * (p5 - 1))
            = 2990 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 37 := by nlinarith [hbnd]
        by_cases hden : 3168 < (3168 - 2990) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
            hchain 13 p4 (by norm_num) hp4 hd2 hd4
          have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
            hchain 23 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 23 37).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((3168 - 2990) * v - 3168) ∣ (3168 * v - 3168 + 2) ∧
                Nat.Prime ((3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168)) ∧
                v < (3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_13, hch3_23, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 23 37).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((3168 - 2990) * v - 3168) ∣ (3168 * v - 3168 + 2) ∧
                Nat.Prime ((3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168)) ∧
                v < (3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 29
        have heq3 : 4032 * ((p4 - 1) * (p5 - 1))
            = 3770 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 32 := by nlinarith [hbnd]
        by_cases hden : 4032 < (4032 - 3770) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
            hchain 13 p4 (by norm_num) hp4 hd2 hd4
          have hch3_29 : ¬ (29:ℕ) ∣ (p4 - 1) :=
            hchain 29 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 29 32).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((4032 - 3770) * v - 4032) ∣ (4032 * v - 4032 + 2) ∧
                Nat.Prime ((4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032)) ∧
                v < (4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_13, hch3_29, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 29 32).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((4032 - 3770) * v - 4032) ∣ (4032 * v - 4032 + 2) ∧
                Nat.Prime ((4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032)) ∧
                v < (4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- p2 = 17
      have heq2 : 192 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 170 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 29 := by
        by_contra hge
        exact cap_kill_3 (c := 29) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
        hchain 5 p3 (by norm_num) hp3 hd1 hd3
      have hch2_17 : ¬ (17:ℕ) ∣ (p3 - 1) :=
        hchain 17 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 17 29).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_17⟩
      have hset2 : (Finset.Ioo 17 29).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1))
          = ({19, 23} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 19
        have heq3 : 3456 * ((p4 - 1) * (p5 - 1))
            = 3230 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 32 := by nlinarith [hbnd]
        by_cases hden : 3456 < (3456 - 3230) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
            hchain 17 p4 (by norm_num) hp4 hd2 hd4
          have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
            hchain 19 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 19 32).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3456 - 3230) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_17, hch3_19, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 19 32).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3456 - 3230) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 23
        have heq3 : 4224 * ((p4 - 1) * (p5 - 1))
            = 3910 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 28 := by nlinarith [hbnd]
        by_cases hden : 4224 < (4224 - 3910) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
            hchain 17 p4 (by norm_num) hp4 hd2 hd4
          have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
            hchain 23 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 23 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((4224 - 3910) * v - 4224) ∣ (4224 * v - 4224 + 2) ∧
                Nat.Prime ((4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224)) ∧
                v < (4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_17, hch3_23, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 23 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((4224 - 3910) * v - 4224) ∣ (4224 * v - 4224 + 2) ∧
                Nat.Prime ((4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224)) ∧
                v < (4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- p2 = 19
      have heq2 : 216 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 190 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 29 := by
        by_contra hge
        exact cap_kill_3 (c := 29) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
        hchain 5 p3 (by norm_num) hp3 hd1 hd3
      have hch2_19 : ¬ (19:ℕ) ∣ (p3 - 1) :=
        hchain 19 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 19 29).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_19⟩
      have hset2 : (Finset.Ioo 19 29).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
          = ({23} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 23
        have heq3 : 4752 * ((p4 - 1) * (p5 - 1))
            = 4370 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 26 := by nlinarith [hbnd]
        by_cases hden : 4752 < (4752 - 4370) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
            hchain 5 p4 (by norm_num) hp4 hd1 hd4
          have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
            hchain 19 p4 (by norm_num) hp4 hd2 hd4
          have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
            hchain 23 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 23 26).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((4752 - 4370) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
                Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752)) ∧
                v < (4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_5, hch3_19, hch3_23, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 23 26).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((4752 - 4370) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
                Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752)) ∧
                v < (4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
  · -- p1 = 7
    have heq1 : 18 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * (p5 - 1))))
        = 14 * (p2 * (p3 * (p4 * p5))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : p2 < 17 := by
      by_contra hge
      exact cap_kill_4 (c := 17) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le heq1
    have hch1_7 : ¬ (7:ℕ) ∣ (p2 - 1) :=
      hchain 7 p2 (by norm_num) hp2 hd1 hd2
    have hmem1 : p2 ∈ (Finset.Ioo 7 17).filter
        (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_7⟩
    have hset1 : (Finset.Ioo 7 17).filter
        (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1))
        = ({11, 13} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- p2 = 11
      have heq2 : 180 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 154 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 23 := by
        by_contra hge
        exact cap_kill_3 (c := 23) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (p3 - 1) :=
        hchain 7 p3 (by norm_num) hp3 hd1 hd3
      have hch2_11 : ¬ (11:ℕ) ∣ (p3 - 1) :=
        hchain 11 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 11 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_7, hch2_11⟩
      have hset2 : (Finset.Ioo 11 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1))
          = ({13, 17, 19} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 13
        have heq3 : 2160 * ((p4 - 1) * (p5 - 1))
            = 2002 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 28 := by nlinarith [hbnd]
        by_cases hden : 2160 < (2160 - 2002) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd1 hd4
          have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
            hchain 11 p4 (by norm_num) hp4 hd2 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
            hchain 13 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 13 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ((2160 - 2002) * v - 2160) ∣ (2160 * v - 2160 + 2) ∧
                Nat.Prime ((2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160)) ∧
                v < (2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_7, hch3_11, hch3_13, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 13 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ((2160 - 2002) * v - 2160) ∣ (2160 * v - 2160 + 2) ∧
                Nat.Prime ((2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160)) ∧
                v < (2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 17
        have heq3 : 2880 * ((p4 - 1) * (p5 - 1))
            = 2618 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 23 := by nlinarith [hbnd]
        by_cases hden : 2880 < (2880 - 2618) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd1 hd4
          have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
            hchain 11 p4 (by norm_num) hp4 hd2 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
            hchain 17 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 17 23).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2880 - 2618) * v - 2880) ∣ (2880 * v - 2880 + 2) ∧
                Nat.Prime ((2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880)) ∧
                v < (2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_7, hch3_11, hch3_17, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 17 23).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2880 - 2618) * v - 2880) ∣ (2880 * v - 2880 + 2) ∧
                Nat.Prime ((2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880)) ∧
                v < (2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 19
        have heq3 : 3240 * ((p4 - 1) * (p5 - 1))
            = 2926 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 22 := by nlinarith [hbnd]
        by_cases hden : 3240 < (3240 - 2926) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd1 hd4
          have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
            hchain 11 p4 (by norm_num) hp4 hd2 hd4
          have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
            hchain 19 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 19 22).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3240 - 2926) * v - 3240) ∣ (3240 * v - 3240 + 2) ∧
                Nat.Prime ((3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240)) ∧
                v < (3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_7, hch3_11, hch3_19, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 19 22).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3240 - 2926) * v - 3240) ∣ (3240 * v - 3240 + 2) ∧
                Nat.Prime ((3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240)) ∧
                v < (3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- p2 = 13
      have heq2 : 216 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 182 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 19 := by
        by_contra hge
        exact cap_kill_3 (c := 19) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (p3 - 1) :=
        hchain 7 p3 (by norm_num) hp3 hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (p3 - 1) :=
        hchain 13 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 13 19).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_7, hch2_13⟩
      have hset2 : (Finset.Ioo 13 19).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = ({17} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 17
        have heq3 : 3456 * ((p4 - 1) * (p5 - 1))
            = 3094 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 20 := by nlinarith [hbnd]
        by_cases hden : 3456 < (3456 - 3094) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
            hchain 13 p4 (by norm_num) hp4 hd2 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
            hchain 17 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 17 20).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((3456 - 3094) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_7, hch3_13, hch3_17, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 17 20).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((3456 - 3094) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
  · -- p1 = 11
    have heq1 : 30 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * (p5 - 1))))
        = 22 * (p2 * (p3 * (p4 * p5))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : p2 < 17 := by
      by_contra hge
      exact cap_kill_4 (c := 17) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le heq1
    have hch1_11 : ¬ (11:ℕ) ∣ (p2 - 1) :=
      hchain 11 p2 (by norm_num) hp2 hd1 hd2
    have hmem1 : p2 ∈ (Finset.Ioo 11 17).filter
        (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_11⟩
    have hset1 : (Finset.Ioo 11 17).filter
        (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1))
        = ({13} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- p2 = 13
      have heq2 : 360 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 286 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 17 := by
        by_contra hge
        exact cap_kill_3 (c := 17) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_11 : ¬ (11:ℕ) ∣ (p3 - 1) :=
        hchain 11 p3 (by norm_num) hp3 hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (p3 - 1) :=
        hchain 13 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 13 17).filter
          (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_11, hch2_13⟩
      have hset2 : (Finset.Ioo 13 17).filter
          (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = (∅ : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      simp at hmem2

#print axioms omega5_empty

end EG411Structure