-- AUTO-GENERATED by oracle/data_engine/omega_ladder/codegen.py (emit_lean_proof_multifile).
-- Certified kill-tree for omega = 5: 3*phi(n) = 2n+2 has NO solution with 5 distinct prime factors.
-- Part of a genuinely parallel-compilable cross-file split -- see emit_lean_proof_multifile's docstring.
-- Capstone: imports all 2 chunk module(s) below (each its own, separately/
-- concurrently compiled .olean) and applies them at the tree's call sites -- the exact
-- same `exact <name> ...` call the same-file chunker emits, just now resolving across
-- an import instead of a same-file declaration (both live in namespace EG411Structure).
import SolutionStructure
import OmegaTreeSupport
import Omega5ChunkMF1
import Omega5ChunkMF2

namespace EG411Structure

set_option linter.style.nativeDecide false

set_option maxRecDepth 8000 in
set_option maxHeartbeats 0 in
theorem omega5_empty (n : ℕ) (hn : 3 * Nat.totient n = 2 * n + 2)
    (p1 p2 p3 p4 p5 : ℕ) (hp1 : p1.Prime) (hp2 : p2.Prime) (hp3 : p3.Prime) (hp4 : p4.Prime) (hp5 : p5.Prime)
    (h1 : p1 < p2) (h2 : p2 < p3) (h3 : p3 < p4) (h4 : p4 < p5)
    (hN : n = p1 * (p2 * (p3 * (p4 * p5)))) : False := by
  have hN' : n = p1 * (p2 * (p3 * (p4 * p5))) := hN
  have hd1 : p1 ∣ n := ⟨p2 * (p3 * (p4 * p5)), hN'⟩
  have hd2 : p2 ∣ n := ⟨p1 * (p3 * (p4 * p5)), by rw [hN']; ring⟩
  have hd3 : p3 ∣ n := ⟨p1 * (p2 * (p4 * p5)), by rw [hN']; ring⟩
  have hd4 : p4 ∣ n := ⟨p1 * (p2 * (p3 * p5)), by rw [hN']; ring⟩
  have hge5 : 5 ≤ p1 := solution_min_prime_ge_five hn p1 hp1 hd1
  have hchain := solution_no_prime_chain hn
  have heq0 : 3 * ((p1 - 1) * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))))
      = 2 * (p1 * (p2 * (p3 * (p4 * p5)))) + 2 := by
    have h := hn
    rw [hN', phi_prod_5 hp1 hp2 hp3 hp4 hp5 h1 h2 h3 h4] at h
    exact h
  have hcap0 : p1 < 13 := by
    by_contra hge
    exact cap_kill_5 (c := 13) (by norm_num) (by norm_num) (by omega)
      h1.le h2.le h3.le h4.le heq0
  have hmem0 : p1 ∈ (Finset.Ioo 4 13).filter
      (fun v => Nat.Prime v) :=
    Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap0⟩, hp1⟩
  have hset0 : (Finset.Ioo 4 13).filter
      (fun v => Nat.Prime v)
      = ({5, 7, 11} : Finset ℕ) := by native_decide
  rw [hset0] at hmem0
  fin_cases hmem0
  · -- p1 = 5
    have heq1 : 12 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * (p5 - 1))))
        = 10 * (p2 * (p3 * (p4 * p5))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    exact omega5_chunk_1 n hn p2 p3 p4 p5 hp2 hp3 hp4 hp5 h1 h2 h3 h4 hd1 hd2 hd3 hd4 heq1
  · -- p1 = 7
    have heq1 : 18 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * (p5 - 1))))
        = 14 * (p2 * (p3 * (p4 * p5))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : p2 < 17 := by
      by_contra hge
      exact cap_kill_4 (c := 17) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le heq1
    have hch1_7 : ¬ (7:ℕ) ∣ (p2 - 1) :=
      hchain 7 p2 (by norm_num) hp2 hd1 hd2
    have hmem1 : p2 ∈ (Finset.Ioo 7 17).filter
        (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_7⟩
    have hset1 : (Finset.Ioo 7 17).filter
        (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1))
        = ({11, 13} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- p2 = 11
      have heq2 : 180 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 154 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 23 := by
        by_contra hge
        exact cap_kill_3 (c := 23) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (p3 - 1) :=
        hchain 7 p3 (by norm_num) hp3 hd1 hd3
      have hch2_11 : ¬ (11:ℕ) ∣ (p3 - 1) :=
        hchain 11 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 11 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_7, hch2_11⟩
      have hset2 : (Finset.Ioo 11 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1))
          = ({13, 17, 19} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 13
        have heq3 : 2160 * ((p4 - 1) * (p5 - 1))
            = 2002 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 28 := by nlinarith [hbnd]
        by_cases hden : 2160 < (2160 - 2002) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd1 hd4
          have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
            hchain 11 p4 (by norm_num) hp4 hd2 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
            hchain 13 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 13 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ((2160 - 2002) * v - 2160) ∣ (2160 * v - 2160 + 2) ∧
                Nat.Prime ((2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160)) ∧
                v < (2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_7, hch3_11, hch3_13, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 13 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ((2160 - 2002) * v - 2160) ∣ (2160 * v - 2160 + 2) ∧
                Nat.Prime ((2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160)) ∧
                v < (2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 17
        have heq3 : 2880 * ((p4 - 1) * (p5 - 1))
            = 2618 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 23 := by nlinarith [hbnd]
        by_cases hden : 2880 < (2880 - 2618) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd1 hd4
          have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
            hchain 11 p4 (by norm_num) hp4 hd2 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
            hchain 17 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 17 23).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2880 - 2618) * v - 2880) ∣ (2880 * v - 2880 + 2) ∧
                Nat.Prime ((2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880)) ∧
                v < (2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_7, hch3_11, hch3_17, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 17 23).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2880 - 2618) * v - 2880) ∣ (2880 * v - 2880 + 2) ∧
                Nat.Prime ((2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880)) ∧
                v < (2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- p3 = 19
        have heq3 : 3240 * ((p4 - 1) * (p5 - 1))
            = 2926 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 22 := by nlinarith [hbnd]
        by_cases hden : 3240 < (3240 - 2926) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd1 hd4
          have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
            hchain 11 p4 (by norm_num) hp4 hd2 hd4
          have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
            hchain 19 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 19 22).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3240 - 2926) * v - 3240) ∣ (3240 * v - 3240 + 2) ∧
                Nat.Prime ((3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240)) ∧
                v < (3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_7, hch3_11, hch3_19, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 19 22).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3240 - 2926) * v - 3240) ∣ (3240 * v - 3240 + 2) ∧
                Nat.Prime ((3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240)) ∧
                v < (3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- p2 = 13
      have heq2 : 216 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 182 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 19 := by
        by_contra hge
        exact cap_kill_3 (c := 19) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (p3 - 1) :=
        hchain 7 p3 (by norm_num) hp3 hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (p3 - 1) :=
        hchain 13 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 13 19).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_7, hch2_13⟩
      have hset2 : (Finset.Ioo 13 19).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = ({17} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 17
        have heq3 : 3456 * ((p4 - 1) * (p5 - 1))
            = 3094 * (p4 * p5) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ p4 := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : p4 ≤ 20 := by nlinarith [hbnd]
        by_cases hden : 3456 < (3456 - 3094) * p4
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
            hchain 7 p4 (by norm_num) hp4 hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
            hchain 13 p4 (by norm_num) hp4 hd2 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
            hchain 17 p4 (by norm_num) hp4 hd3 hd4
          have hmem3 : p4 ∈ (Finset.Ioc 17 20).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((3456 - 3094) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hp4, hch3_7, hch3_13, hch3_17, hdvd,
              by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 17 20).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((3456 - 3094) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
  · -- p1 = 11
    have heq1 : 30 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * (p5 - 1))))
        = 22 * (p2 * (p3 * (p4 * p5))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : p2 < 17 := by
      by_contra hge
      exact cap_kill_4 (c := 17) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le heq1
    have hch1_11 : ¬ (11:ℕ) ∣ (p2 - 1) :=
      hchain 11 p2 (by norm_num) hp2 hd1 hd2
    have hmem1 : p2 ∈ (Finset.Ioo 11 17).filter
        (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_11⟩
    have hset1 : (Finset.Ioo 11 17).filter
        (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1))
        = ({13} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- p2 = 13
      have heq2 : 360 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
          = 286 * (p3 * (p4 * p5)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 17 := by
        by_contra hge
        exact cap_kill_3 (c := 17) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_11 : ¬ (11:ℕ) ∣ (p3 - 1) :=
        hchain 11 p3 (by norm_num) hp3 hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (p3 - 1) :=
        hchain 13 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 13 17).filter
          (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_11, hch2_13⟩
      have hset2 : (Finset.Ioo 13 17).filter
          (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = (∅ : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      simp at hmem2

#print axioms omega5_empty

end EG411Structure