-- AUTO-GENERATED by oracle/data_engine/omega_ladder/codegen.py (emit_lean_proof_multifile).
-- Certified kill-tree for omega = 6: 3*phi(n) = 2n+2 has NO solution with 6 distinct prime factors.
-- Part of a genuinely parallel-compilable cross-file split -- see emit_lean_proof_multifile's docstring.
-- Capstone: imports all 5 chunk module(s) below (each its own, separately/
-- concurrently compiled .olean) and applies them at the tree's call sites -- the exact
-- same `exact <name> ...` call the same-file chunker emits, just now resolving across
-- an import instead of a same-file declaration (both live in namespace EG411Structure).
import SolutionStructure
import OmegaTreeSupport
import Omega6ChunkMF1
import Omega6ChunkMF2
import Omega6ChunkMF3
import Omega6ChunkMF4
import Omega6ChunkMF5

namespace EG411Structure

set_option linter.style.nativeDecide false

set_option maxRecDepth 8000 in
set_option maxHeartbeats 0 in
theorem omega6_empty (n : ℕ) (hn : 3 * Nat.totient n = 2 * n + 2)
    (p1 p2 p3 p4 p5 p6 : ℕ) (hp1 : p1.Prime) (hp2 : p2.Prime) (hp3 : p3.Prime) (hp4 : p4.Prime) (hp5 : p5.Prime) (hp6 : p6.Prime)
    (h1 : p1 < p2) (h2 : p2 < p3) (h3 : p3 < p4) (h4 : p4 < p5) (h5 : p5 < p6)
    (hN : n = p1 * (p2 * (p3 * (p4 * (p5 * p6))))) : False := by
  have hN' : n = p1 * (p2 * (p3 * (p4 * (p5 * p6)))) := hN
  have hd1 : p1 ∣ n := ⟨p2 * (p3 * (p4 * (p5 * p6))), hN'⟩
  have hd2 : p2 ∣ n := ⟨p1 * (p3 * (p4 * (p5 * p6))), by rw [hN']; ring⟩
  have hd3 : p3 ∣ n := ⟨p1 * (p2 * (p4 * (p5 * p6))), by rw [hN']; ring⟩
  have hd4 : p4 ∣ n := ⟨p1 * (p2 * (p3 * (p5 * p6))), by rw [hN']; ring⟩
  have hd5 : p5 ∣ n := ⟨p1 * (p2 * (p3 * (p4 * p6))), by rw [hN']; ring⟩
  have hge5 : 5 ≤ p1 := solution_min_prime_ge_five hn p1 hp1 hd1
  have hchain := solution_no_prime_chain hn
  have heq0 : 3 * ((p1 - 1) * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))))
      = 2 * (p1 * (p2 * (p3 * (p4 * (p5 * p6))))) + 2 := by
    have h := hn
    rw [hN', phi_prod_6 hp1 hp2 hp3 hp4 hp5 hp6 h1 h2 h3 h4 h5] at h
    exact h
  have hcap0 : p1 < 17 := by
    by_contra hge
    exact cap_kill_6 (c := 17) (by norm_num) (by norm_num) (by omega)
      h1.le h2.le h3.le h4.le h5.le heq0
  have hmem0 : p1 ∈ (Finset.Ioo 4 17).filter
      (fun v => Nat.Prime v) :=
    Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap0⟩, hp1⟩
  have hset0 : (Finset.Ioo 4 17).filter
      (fun v => Nat.Prime v)
      = ({5, 7, 11, 13} : Finset ℕ) := by native_decide
  rw [hset0] at hmem0
  fin_cases hmem0
  · -- p1 = 5
    have heq1 : 12 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))))
        = 10 * (p2 * (p3 * (p4 * (p5 * p6)))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    exact omega6_chunk_1 n hn p2 p3 p4 p5 p6 hp2 hp3 hp4 hp5 hp6 h1 h2 h3 h4 h5 hd1 hd2 hd3 hd4 hd5 heq1
  · -- p1 = 7
    have heq1 : 18 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))))
        = 14 * (p2 * (p3 * (p4 * (p5 * p6)))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : p2 < 23 := by
      by_contra hge
      exact cap_kill_5 (c := 23) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le h5.le heq1
    have hch1_7 : ¬ (7:ℕ) ∣ (p2 - 1) :=
      hchain 7 p2 (by norm_num) hp2 hd1 hd2
    have hmem1 : p2 ∈ (Finset.Ioo 7 23).filter
        (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_7⟩
    have hset1 : (Finset.Ioo 7 23).filter
        (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1))
        = ({11, 13, 17, 19} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- p2 = 11
      have heq2 : 180 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
          = 154 * (p3 * (p4 * (p5 * p6))) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 29 := by
        by_contra hge
        exact cap_kill_4 (c := 29) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le h5.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (p3 - 1) :=
        hchain 7 p3 (by norm_num) hp3 hd1 hd3
      have hch2_11 : ¬ (11:ℕ) ∣ (p3 - 1) :=
        hchain 11 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 11 29).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_7, hch2_11⟩
      have hset2 : (Finset.Ioo 11 29).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1))
          = ({13, 17, 19} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 13
        have heq3 : 2160 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
            = 2002 * (p4 * (p5 * p6)) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hcap3 : p4 < 41 := by
          by_contra hge
          exact cap_kill_3 (c := 41) (by norm_num) (by norm_num) (by omega)
            h4.le h5.le heq3
        have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
          hchain 7 p4 (by norm_num) hp4 hd1 hd4
        have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
          hchain 11 p4 (by norm_num) hp4 hd2 hd4
        have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
          hchain 13 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioo 13 41).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_7, hch3_11, hch3_13⟩
        have hset3 : (Finset.Ioo 13 41).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
            = ({17, 19, 31, 37} : Finset ℕ) := by native_decide
        rw [hset3] at hmem3
        fin_cases hmem3
        · -- p4 = 17
          have heq4 : 34560 * ((p5 - 1) * (p6 - 1))
              = 34034 * (p5 * p6) + 2 := by
            ring_nf at heq3 ⊢
            omega
          have hs2 : 2 ≤ p5 := by omega
          have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
          have hshi : p5 ≤ 132 := by nlinarith [hbnd]
          by_cases hden : 34560 < (34560 - 34034) * p5
          · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
            have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
              hchain 7 p5 (by norm_num) hp5 hd1 hd5
            have hch4_11 : ¬ (11:ℕ) ∣ (p5 - 1) :=
              hchain 11 p5 (by norm_num) hp5 hd2 hd5
            have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
              hchain 13 p5 (by norm_num) hp5 hd3 hd5
            have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
              hchain 17 p5 (by norm_num) hp5 hd4 hd5
            have hmem4 : p5 ∈ (Finset.Ioc 17 132).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ((34560 - 34034) * v - 34560) ∣ (34560 * v - 34560 + 2) ∧
                  Nat.Prime ((34560 * v - 34560 + 2) / ((34560 - 34034) * v - 34560)) ∧
                  v < (34560 * v - 34560 + 2) / ((34560 - 34034) * v - 34560)) :=
              Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
                hp5, hch4_7, hch4_11, hch4_13, hch4_17, hdvd,
                by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
            have hempty : (Finset.Ioc 17 132).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ((34560 - 34034) * v - 34560) ∣ (34560 * v - 34560 + 2) ∧
                  Nat.Prime ((34560 * v - 34560 + 2) / ((34560 - 34034) * v - 34560)) ∧
                  v < (34560 * v - 34560 + 2) / ((34560 - 34034) * v - 34560))
                = ∅ := by native_decide
            rw [hempty] at hmem4
            simp at hmem4
          · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
        · -- p4 = 19
          have heq4 : 38880 * ((p5 - 1) * (p6 - 1))
              = 38038 * (p5 * p6) + 2 := by
            ring_nf at heq3 ⊢
            omega
          have hs2 : 2 ≤ p5 := by omega
          have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
          have hshi : p5 ≤ 93 := by nlinarith [hbnd]
          by_cases hden : 38880 < (38880 - 38038) * p5
          · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
            have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
              hchain 7 p5 (by norm_num) hp5 hd1 hd5
            have hch4_11 : ¬ (11:ℕ) ∣ (p5 - 1) :=
              hchain 11 p5 (by norm_num) hp5 hd2 hd5
            have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
              hchain 13 p5 (by norm_num) hp5 hd3 hd5
            have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
              hchain 19 p5 (by norm_num) hp5 hd4 hd5
            have hmem4 : p5 ∈ (Finset.Ioc 19 93).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 19 ∣ (v - 1) ∧
                  ((38880 - 38038) * v - 38880) ∣ (38880 * v - 38880 + 2) ∧
                  Nat.Prime ((38880 * v - 38880 + 2) / ((38880 - 38038) * v - 38880)) ∧
                  v < (38880 * v - 38880 + 2) / ((38880 - 38038) * v - 38880)) :=
              Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
                hp5, hch4_7, hch4_11, hch4_13, hch4_19, hdvd,
                by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
            have hempty : (Finset.Ioc 19 93).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 19 ∣ (v - 1) ∧
                  ((38880 - 38038) * v - 38880) ∣ (38880 * v - 38880 + 2) ∧
                  Nat.Prime ((38880 * v - 38880 + 2) / ((38880 - 38038) * v - 38880)) ∧
                  v < (38880 * v - 38880 + 2) / ((38880 - 38038) * v - 38880))
                = ∅ := by native_decide
            rw [hempty] at hmem4
            simp at hmem4
          · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
        · -- p4 = 31
          have heq4 : 64800 * ((p5 - 1) * (p6 - 1))
              = 62062 * (p5 * p6) + 2 := by
            ring_nf at heq3 ⊢
            omega
          have hs2 : 2 ≤ p5 := by omega
          have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
          have hshi : p5 ≤ 48 := by nlinarith [hbnd]
          by_cases hden : 64800 < (64800 - 62062) * p5
          · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
            have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
              hchain 7 p5 (by norm_num) hp5 hd1 hd5
            have hch4_11 : ¬ (11:ℕ) ∣ (p5 - 1) :=
              hchain 11 p5 (by norm_num) hp5 hd2 hd5
            have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
              hchain 13 p5 (by norm_num) hp5 hd3 hd5
            have hch4_31 : ¬ (31:ℕ) ∣ (p5 - 1) :=
              hchain 31 p5 (by norm_num) hp5 hd4 hd5
            have hmem4 : p5 ∈ (Finset.Ioc 31 48).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 31 ∣ (v - 1) ∧
                  ((64800 - 62062) * v - 64800) ∣ (64800 * v - 64800 + 2) ∧
                  Nat.Prime ((64800 * v - 64800 + 2) / ((64800 - 62062) * v - 64800)) ∧
                  v < (64800 * v - 64800 + 2) / ((64800 - 62062) * v - 64800)) :=
              Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
                hp5, hch4_7, hch4_11, hch4_13, hch4_31, hdvd,
                by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
            have hempty : (Finset.Ioc 31 48).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 31 ∣ (v - 1) ∧
                  ((64800 - 62062) * v - 64800) ∣ (64800 * v - 64800 + 2) ∧
                  Nat.Prime ((64800 * v - 64800 + 2) / ((64800 - 62062) * v - 64800)) ∧
                  v < (64800 * v - 64800 + 2) / ((64800 - 62062) * v - 64800))
                = ∅ := by native_decide
            rw [hempty] at hmem4
            simp at hmem4
          · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
        · -- p4 = 37
          have heq4 : 77760 * ((p5 - 1) * (p6 - 1))
              = 74074 * (p5 * p6) + 2 := by
            ring_nf at heq3 ⊢
            omega
          have hs2 : 2 ≤ p5 := by omega
          have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
          have hshi : p5 ≤ 43 := by nlinarith [hbnd]
          by_cases hden : 77760 < (77760 - 74074) * p5
          · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
            have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
              hchain 7 p5 (by norm_num) hp5 hd1 hd5
            have hch4_11 : ¬ (11:ℕ) ∣ (p5 - 1) :=
              hchain 11 p5 (by norm_num) hp5 hd2 hd5
            have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
              hchain 13 p5 (by norm_num) hp5 hd3 hd5
            have hch4_37 : ¬ (37:ℕ) ∣ (p5 - 1) :=
              hchain 37 p5 (by norm_num) hp5 hd4 hd5
            have hmem4 : p5 ∈ (Finset.Ioc 37 43).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 37 ∣ (v - 1) ∧
                  ((77760 - 74074) * v - 77760) ∣ (77760 * v - 77760 + 2) ∧
                  Nat.Prime ((77760 * v - 77760 + 2) / ((77760 - 74074) * v - 77760)) ∧
                  v < (77760 * v - 77760 + 2) / ((77760 - 74074) * v - 77760)) :=
              Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
                hp5, hch4_7, hch4_11, hch4_13, hch4_37, hdvd,
                by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
            have hempty : (Finset.Ioc 37 43).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 37 ∣ (v - 1) ∧
                  ((77760 - 74074) * v - 77760) ∣ (77760 * v - 77760 + 2) ∧
                  Nat.Prime ((77760 * v - 77760 + 2) / ((77760 - 74074) * v - 77760)) ∧
                  v < (77760 * v - 77760 + 2) / ((77760 - 74074) * v - 77760))
                = ∅ := by native_decide
            rw [hempty] at hmem4
            simp at hmem4
          · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p3 = 17
        have heq3 : 2880 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
            = 2618 * (p4 * (p5 * p6)) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hcap3 : p4 < 37 := by
          by_contra hge
          exact cap_kill_3 (c := 37) (by norm_num) (by norm_num) (by omega)
            h4.le h5.le heq3
        have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
          hchain 7 p4 (by norm_num) hp4 hd1 hd4
        have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
          hchain 11 p4 (by norm_num) hp4 hd2 hd4
        have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
          hchain 17 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioo 17 37).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_7, hch3_11, hch3_17⟩
        have hset3 : (Finset.Ioo 17 37).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1))
            = ({19, 31} : Finset ℕ) := by native_decide
        rw [hset3] at hmem3
        fin_cases hmem3
        · -- p4 = 19
          have heq4 : 51840 * ((p5 - 1) * (p6 - 1))
              = 49742 * (p5 * p6) + 2 := by
            ring_nf at heq3 ⊢
            omega
          have hs2 : 2 ≤ p5 := by omega
          have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
          have hshi : p5 ≤ 50 := by nlinarith [hbnd]
          by_cases hden : 51840 < (51840 - 49742) * p5
          · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
            have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
              hchain 7 p5 (by norm_num) hp5 hd1 hd5
            have hch4_11 : ¬ (11:ℕ) ∣ (p5 - 1) :=
              hchain 11 p5 (by norm_num) hp5 hd2 hd5
            have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
              hchain 17 p5 (by norm_num) hp5 hd3 hd5
            have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
              hchain 19 p5 (by norm_num) hp5 hd4 hd5
            have hmem4 : p5 ∈ (Finset.Ioc 19 50).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ¬ 19 ∣ (v - 1) ∧
                  ((51840 - 49742) * v - 51840) ∣ (51840 * v - 51840 + 2) ∧
                  Nat.Prime ((51840 * v - 51840 + 2) / ((51840 - 49742) * v - 51840)) ∧
                  v < (51840 * v - 51840 + 2) / ((51840 - 49742) * v - 51840)) :=
              Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
                hp5, hch4_7, hch4_11, hch4_17, hch4_19, hdvd,
                by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
            have hempty : (Finset.Ioc 19 50).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ¬ 19 ∣ (v - 1) ∧
                  ((51840 - 49742) * v - 51840) ∣ (51840 * v - 51840 + 2) ∧
                  Nat.Prime ((51840 * v - 51840 + 2) / ((51840 - 49742) * v - 51840)) ∧
                  v < (51840 * v - 51840 + 2) / ((51840 - 49742) * v - 51840))
                = ∅ := by native_decide
            rw [hempty] at hmem4
            simp at hmem4
          · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
        · -- p4 = 31
          have heq4 : 86400 * ((p5 - 1) * (p6 - 1))
              = 81158 * (p5 * p6) + 2 := by
            ring_nf at heq3 ⊢
            omega
          have hs2 : 2 ≤ p5 := by omega
          have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
          have hshi : p5 ≤ 34 := by nlinarith [hbnd]
          by_cases hden : 86400 < (86400 - 81158) * p5
          · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
            have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
              hchain 7 p5 (by norm_num) hp5 hd1 hd5
            have hch4_11 : ¬ (11:ℕ) ∣ (p5 - 1) :=
              hchain 11 p5 (by norm_num) hp5 hd2 hd5
            have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
              hchain 17 p5 (by norm_num) hp5 hd3 hd5
            have hch4_31 : ¬ (31:ℕ) ∣ (p5 - 1) :=
              hchain 31 p5 (by norm_num) hp5 hd4 hd5
            have hmem4 : p5 ∈ (Finset.Ioc 31 34).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ¬ 31 ∣ (v - 1) ∧
                  ((86400 - 81158) * v - 86400) ∣ (86400 * v - 86400 + 2) ∧
                  Nat.Prime ((86400 * v - 86400 + 2) / ((86400 - 81158) * v - 86400)) ∧
                  v < (86400 * v - 86400 + 2) / ((86400 - 81158) * v - 86400)) :=
              Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
                hp5, hch4_7, hch4_11, hch4_17, hch4_31, hdvd,
                by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
            have hempty : (Finset.Ioc 31 34).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 11 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ¬ 31 ∣ (v - 1) ∧
                  ((86400 - 81158) * v - 86400) ∣ (86400 * v - 86400 + 2) ∧
                  Nat.Prime ((86400 * v - 86400 + 2) / ((86400 - 81158) * v - 86400)) ∧
                  v < (86400 * v - 86400 + 2) / ((86400 - 81158) * v - 86400))
                = ∅ := by native_decide
            rw [hempty] at hmem4
            simp at hmem4
          · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p3 = 19
        have heq3 : 3240 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
            = 2926 * (p4 * (p5 * p6)) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hcap3 : p4 < 31 := by
          by_contra hge
          exact cap_kill_3 (c := 31) (by norm_num) (by norm_num) (by omega)
            h4.le h5.le heq3
        have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
          hchain 7 p4 (by norm_num) hp4 hd1 hd4
        have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
          hchain 11 p4 (by norm_num) hp4 hd2 hd4
        have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
          hchain 19 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioo 19 31).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_7, hch3_11, hch3_19⟩
        have hset3 : (Finset.Ioo 19 31).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
            = (∅ : Finset ℕ) := by native_decide
        rw [hset3] at hmem3
        simp at hmem3
    · -- p2 = 13
      have heq2 : 216 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
          = 182 * (p3 * (p4 * (p5 * p6))) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 29 := by
        by_contra hge
        exact cap_kill_4 (c := 29) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le h5.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (p3 - 1) :=
        hchain 7 p3 (by norm_num) hp3 hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (p3 - 1) :=
        hchain 13 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 13 29).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_7, hch2_13⟩
      have hset2 : (Finset.Ioo 13 29).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = ({17, 19, 23} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 17
        have heq3 : 3456 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
            = 3094 * (p4 * (p5 * p6)) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hcap3 : p4 < 29 := by
          by_contra hge
          exact cap_kill_3 (c := 29) (by norm_num) (by norm_num) (by omega)
            h4.le h5.le heq3
        have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
          hchain 7 p4 (by norm_num) hp4 hd1 hd4
        have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
          hchain 13 p4 (by norm_num) hp4 hd2 hd4
        have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
          hchain 17 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioo 17 29).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_7, hch3_13, hch3_17⟩
        have hset3 : (Finset.Ioo 17 29).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1))
            = ({19, 23} : Finset ℕ) := by native_decide
        rw [hset3] at hmem3
        fin_cases hmem3
        · -- p4 = 19
          have heq4 : 62208 * ((p5 - 1) * (p6 - 1))
              = 58786 * (p5 * p6) + 2 := by
            ring_nf at heq3 ⊢
            omega
          have hs2 : 2 ≤ p5 := by omega
          have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
          have hshi : p5 ≤ 37 := by nlinarith [hbnd]
          by_cases hden : 62208 < (62208 - 58786) * p5
          · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
            have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
              hchain 7 p5 (by norm_num) hp5 hd1 hd5
            have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
              hchain 13 p5 (by norm_num) hp5 hd2 hd5
            have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
              hchain 17 p5 (by norm_num) hp5 hd3 hd5
            have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
              hchain 19 p5 (by norm_num) hp5 hd4 hd5
            have hmem4 : p5 ∈ (Finset.Ioc 19 37).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ¬ 19 ∣ (v - 1) ∧
                  ((62208 - 58786) * v - 62208) ∣ (62208 * v - 62208 + 2) ∧
                  Nat.Prime ((62208 * v - 62208 + 2) / ((62208 - 58786) * v - 62208)) ∧
                  v < (62208 * v - 62208 + 2) / ((62208 - 58786) * v - 62208)) :=
              Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
                hp5, hch4_7, hch4_13, hch4_17, hch4_19, hdvd,
                by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
            have hempty : (Finset.Ioc 19 37).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ¬ 19 ∣ (v - 1) ∧
                  ((62208 - 58786) * v - 62208) ∣ (62208 * v - 62208 + 2) ∧
                  Nat.Prime ((62208 * v - 62208 + 2) / ((62208 - 58786) * v - 62208)) ∧
                  v < (62208 * v - 62208 + 2) / ((62208 - 58786) * v - 62208))
                = ∅ := by native_decide
            rw [hempty] at hmem4
            simp at hmem4
          · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
        · -- p4 = 23
          have heq4 : 76032 * ((p5 - 1) * (p6 - 1))
              = 71162 * (p5 * p6) + 2 := by
            ring_nf at heq3 ⊢
            omega
          have hs2 : 2 ≤ p5 := by omega
          have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
          have hshi : p5 ≤ 32 := by nlinarith [hbnd]
          by_cases hden : 76032 < (76032 - 71162) * p5
          · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
            have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
              hchain 7 p5 (by norm_num) hp5 hd1 hd5
            have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
              hchain 13 p5 (by norm_num) hp5 hd2 hd5
            have hch4_17 : ¬ (17:ℕ) ∣ (p5 - 1) :=
              hchain 17 p5 (by norm_num) hp5 hd3 hd5
            have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
              hchain 23 p5 (by norm_num) hp5 hd4 hd5
            have hmem4 : p5 ∈ (Finset.Ioc 23 32).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ¬ 23 ∣ (v - 1) ∧
                  ((76032 - 71162) * v - 76032) ∣ (76032 * v - 76032 + 2) ∧
                  Nat.Prime ((76032 * v - 76032 + 2) / ((76032 - 71162) * v - 76032)) ∧
                  v < (76032 * v - 76032 + 2) / ((76032 - 71162) * v - 76032)) :=
              Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
                hp5, hch4_7, hch4_13, hch4_17, hch4_23, hdvd,
                by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
            have hempty : (Finset.Ioc 23 32).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 17 ∣ (v - 1) ∧
                  ¬ 23 ∣ (v - 1) ∧
                  ((76032 - 71162) * v - 76032) ∣ (76032 * v - 76032 + 2) ∧
                  Nat.Prime ((76032 * v - 76032 + 2) / ((76032 - 71162) * v - 76032)) ∧
                  v < (76032 * v - 76032 + 2) / ((76032 - 71162) * v - 76032))
                = ∅ := by native_decide
            rw [hempty] at hmem4
            simp at hmem4
          · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p3 = 19
        have heq3 : 3888 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
            = 3458 * (p4 * (p5 * p6)) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hcap3 : p4 < 29 := by
          by_contra hge
          exact cap_kill_3 (c := 29) (by norm_num) (by norm_num) (by omega)
            h4.le h5.le heq3
        have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
          hchain 7 p4 (by norm_num) hp4 hd1 hd4
        have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
          hchain 13 p4 (by norm_num) hp4 hd2 hd4
        have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
          hchain 19 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioo 19 29).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_7, hch3_13, hch3_19⟩
        have hset3 : (Finset.Ioo 19 29).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
            = ({23} : Finset ℕ) := by native_decide
        rw [hset3] at hmem3
        fin_cases hmem3
        · -- p4 = 23
          have heq4 : 85536 * ((p5 - 1) * (p6 - 1))
              = 79534 * (p5 * p6) + 2 := by
            ring_nf at heq3 ⊢
            omega
          have hs2 : 2 ≤ p5 := by omega
          have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
          have hshi : p5 ≤ 29 := by nlinarith [hbnd]
          by_cases hden : 85536 < (85536 - 79534) * p5
          · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
            have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
              hchain 7 p5 (by norm_num) hp5 hd1 hd5
            have hch4_13 : ¬ (13:ℕ) ∣ (p5 - 1) :=
              hchain 13 p5 (by norm_num) hp5 hd2 hd5
            have hch4_19 : ¬ (19:ℕ) ∣ (p5 - 1) :=
              hchain 19 p5 (by norm_num) hp5 hd3 hd5
            have hch4_23 : ¬ (23:ℕ) ∣ (p5 - 1) :=
              hchain 23 p5 (by norm_num) hp5 hd4 hd5
            have hmem4 : p5 ∈ (Finset.Ioc 23 29).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 19 ∣ (v - 1) ∧
                  ¬ 23 ∣ (v - 1) ∧
                  ((85536 - 79534) * v - 85536) ∣ (85536 * v - 85536 + 2) ∧
                  Nat.Prime ((85536 * v - 85536 + 2) / ((85536 - 79534) * v - 85536)) ∧
                  v < (85536 * v - 85536 + 2) / ((85536 - 79534) * v - 85536)) :=
              Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
                hp5, hch4_7, hch4_13, hch4_19, hch4_23, hdvd,
                by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
            have hempty : (Finset.Ioc 23 29).filter (fun v =>
                  Nat.Prime v ∧
                  ¬ 7 ∣ (v - 1) ∧
                  ¬ 13 ∣ (v - 1) ∧
                  ¬ 19 ∣ (v - 1) ∧
                  ¬ 23 ∣ (v - 1) ∧
                  ((85536 - 79534) * v - 85536) ∣ (85536 * v - 85536 + 2) ∧
                  Nat.Prime ((85536 * v - 85536 + 2) / ((85536 - 79534) * v - 85536)) ∧
                  v < (85536 * v - 85536 + 2) / ((85536 - 79534) * v - 85536))
                = ∅ := by native_decide
            rw [hempty] at hmem4
            simp at hmem4
          · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
      · -- p3 = 23
        have heq3 : 4752 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
            = 4186 * (p4 * (p5 * p6)) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hcap3 : p4 < 29 := by
          by_contra hge
          exact cap_kill_3 (c := 29) (by norm_num) (by norm_num) (by omega)
            h4.le h5.le heq3
        have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
          hchain 7 p4 (by norm_num) hp4 hd1 hd4
        have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
          hchain 13 p4 (by norm_num) hp4 hd2 hd4
        have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
          hchain 23 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioo 23 29).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_7, hch3_13, hch3_23⟩
        have hset3 : (Finset.Ioo 23 29).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 23 ∣ (v - 1))
            = (∅ : Finset ℕ) := by native_decide
        rw [hset3] at hmem3
        simp at hmem3
    · -- p2 = 17
      have heq2 : 288 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
          = 238 * (p3 * (p4 * (p5 * p6))) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 23 := by
        by_contra hge
        exact cap_kill_4 (c := 23) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le h5.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (p3 - 1) :=
        hchain 7 p3 (by norm_num) hp3 hd1 hd3
      have hch2_17 : ¬ (17:ℕ) ∣ (p3 - 1) :=
        hchain 17 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 17 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_7, hch2_17⟩
      have hset2 : (Finset.Ioo 17 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1))
          = ({19} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 19
        have heq3 : 5184 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
            = 4522 * (p4 * (p5 * p6)) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hcap3 : p4 < 23 := by
          by_contra hge
          exact cap_kill_3 (c := 23) (by norm_num) (by norm_num) (by omega)
            h4.le h5.le heq3
        have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
          hchain 7 p4 (by norm_num) hp4 hd1 hd4
        have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
          hchain 17 p4 (by norm_num) hp4 hd2 hd4
        have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
          hchain 19 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioo 19 23).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_7, hch3_17, hch3_19⟩
        have hset3 : (Finset.Ioo 19 23).filter
            (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
            = (∅ : Finset ℕ) := by native_decide
        rw [hset3] at hmem3
        simp at hmem3
    · -- p2 = 19
      have heq2 : 324 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
          = 266 * (p3 * (p4 * (p5 * p6))) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 23 := by
        by_contra hge
        exact cap_kill_4 (c := 23) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le h5.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (p3 - 1) :=
        hchain 7 p3 (by norm_num) hp3 hd1 hd3
      have hch2_19 : ¬ (19:ℕ) ∣ (p3 - 1) :=
        hchain 19 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 19 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_7, hch2_19⟩
      have hset2 : (Finset.Ioo 19 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
          = (∅ : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      simp at hmem2
  · -- p1 = 11
    have heq1 : 30 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))))
        = 22 * (p2 * (p3 * (p4 * (p5 * p6)))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : p2 < 17 := by
      by_contra hge
      exact cap_kill_5 (c := 17) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le h5.le heq1
    have hch1_11 : ¬ (11:ℕ) ∣ (p2 - 1) :=
      hchain 11 p2 (by norm_num) hp2 hd1 hd2
    have hmem1 : p2 ∈ (Finset.Ioo 11 17).filter
        (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_11⟩
    have hset1 : (Finset.Ioo 11 17).filter
        (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1))
        = ({13} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- p2 = 13
      have heq2 : 360 * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1))))
          = 286 * (p3 * (p4 * (p5 * p6))) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : p3 < 19 := by
        by_contra hge
        exact cap_kill_4 (c := 19) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le h5.le heq2
      have hch2_11 : ¬ (11:ℕ) ∣ (p3 - 1) :=
        hchain 11 p3 (by norm_num) hp3 hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (p3 - 1) :=
        hchain 13 p3 (by norm_num) hp3 hd2 hd3
      have hmem2 : p3 ∈ (Finset.Ioo 13 19).filter
          (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_11, hch2_13⟩
      have hset2 : (Finset.Ioo 13 19).filter
          (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = ({17} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- p3 = 17
        have heq3 : 5760 * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))
            = 4862 * (p4 * (p5 * p6)) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hcap3 : p4 < 19 := by
          by_contra hge
          exact cap_kill_3 (c := 19) (by norm_num) (by norm_num) (by omega)
            h4.le h5.le heq3
        have hch3_11 : ¬ (11:ℕ) ∣ (p4 - 1) :=
          hchain 11 p4 (by norm_num) hp4 hd1 hd4
        have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
          hchain 13 p4 (by norm_num) hp4 hd2 hd4
        have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
          hchain 17 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioo 17 19).filter
            (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_11, hch3_13, hch3_17⟩
        have hset3 : (Finset.Ioo 17 19).filter
            (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1))
            = (∅ : Finset ℕ) := by native_decide
        rw [hset3] at hmem3
        simp at hmem3
  · -- p1 = 13
    have heq1 : 36 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * ((p5 - 1) * (p6 - 1)))))
        = 26 * (p2 * (p3 * (p4 * (p5 * p6)))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : p2 < 17 := by
      by_contra hge
      exact cap_kill_5 (c := 17) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le h5.le heq1
    have hch1_13 : ¬ (13:ℕ) ∣ (p2 - 1) :=
      hchain 13 p2 (by norm_num) hp2 hd1 hd2
    have hmem1 : p2 ∈ (Finset.Ioo 13 17).filter
        (fun v => Nat.Prime v ∧ ¬ 13 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_13⟩
    have hset1 : (Finset.Ioo 13 17).filter
        (fun v => Nat.Prime v ∧ ¬ 13 ∣ (v - 1))
        = (∅ : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    simp at hmem1

#print axioms omega6_empty

end EG411Structure