-- AUTO-GENERATED by oracle/data_engine/omega_ladder/codegen.py (emit_lean_proof_multifile).
-- Certified kill-tree for omega = 5: 3*phi(n) = 2n+2 has NO solution with 5 distinct prime factors.
-- Part of a genuinely parallel-compilable cross-file split -- see emit_lean_proof_multifile's docstring.
-- Chunk 2/2 (omega5_chunk_1): NESTED -- its own subtree exceeded chunk_threshold
-- again, so it calls 1 further chunk(s) below. Depends on those chunks' .olean;
-- the orchestrator must compile them first (see lean-parallel-compile.ts's wave scheduling).
import SolutionStructure
import OmegaTreeSupport
import Omega5ChunkMF1

namespace EG411Structure

set_option linter.style.nativeDecide false

set_option maxRecDepth 8000 in
set_option maxHeartbeats 0 in
theorem omega5_chunk_1 (n : ℕ) (hn : 3 * Nat.totient n = 2 * n + 2)
    (p2 p3 p4 p5 : ℕ) (hp2 : p2.Prime) (hp3 : p3.Prime) (hp4 : p4.Prime) (hp5 : p5.Prime)
    (h1 : (5:ℕ) < p2) (h2 : p2 < p3) (h3 : p3 < p4) (h4 : p4 < p5)
    (hd1 : (5:ℕ) ∣ n) (hd2 : p2 ∣ n) (hd3 : p3 ∣ n) (hd4 : p4 ∣ n)
    (heq1 : 12 * ((p2 - 1) * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))) = 10 * (p2 * (p3 * (p4 * p5))) + 2) : False := by
  have hchain := solution_no_prime_chain hn
  have hcap1 : p2 < 23 := by
    by_contra hge
    exact cap_kill_4 (c := 23) (by norm_num) (by norm_num) (by omega)
      h2.le h3.le h4.le heq1
  have hch1_5 : ¬ (5:ℕ) ∣ (p2 - 1) :=
    hchain 5 p2 (by norm_num) hp2 hd1 hd2
  have hmem1 : p2 ∈ (Finset.Ioo 5 23).filter
      (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1)) :=
    Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hp2, hch1_5⟩
  have hset1 : (Finset.Ioo 5 23).filter
      (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1))
      = ({7, 13, 17, 19} : Finset ℕ) := by native_decide
  rw [hset1] at hmem1
  fin_cases hmem1
  · -- p2 = 7
    have heq2 : 72 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
        = 70 * (p3 * (p4 * p5)) + 2 := by
      ring_nf at heq1 ⊢
      omega
    exact omega5_chunk_2 n hn p3 p4 p5 hp3 hp4 hp5 h2 h3 h4 hd1 hd2 hd3 hd4 heq2
  · -- p2 = 13
    have heq2 : 144 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
        = 130 * (p3 * (p4 * p5)) + 2 := by
      ring_nf at heq1 ⊢
      omega
    have hcap2 : p3 < 31 := by
      by_contra hge
      exact cap_kill_3 (c := 31) (by norm_num) (by norm_num) (by omega)
        h3.le h4.le heq2
    have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
      hchain 5 p3 (by norm_num) hp3 hd1 hd3
    have hch2_13 : ¬ (13:ℕ) ∣ (p3 - 1) :=
      hchain 13 p3 (by norm_num) hp3 hd2 hd3
    have hmem2 : p3 ∈ (Finset.Ioo 13 31).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_13⟩
    have hset2 : (Finset.Ioo 13 31).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
        = ({17, 19, 23, 29} : Finset ℕ) := by native_decide
    rw [hset2] at hmem2
    fin_cases hmem2
    · -- p3 = 17
      have heq3 : 2304 * ((p4 - 1) * (p5 - 1))
          = 2210 * (p4 * p5) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hs2 : 2 ≤ p4 := by omega
      have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
      have hshi : p4 ≤ 50 := by nlinarith [hbnd]
      by_cases hden : 2304 < (2304 - 2210) * p4
      · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
        have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
          hchain 5 p4 (by norm_num) hp4 hd1 hd4
        have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
          hchain 13 p4 (by norm_num) hp4 hd2 hd4
        have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
          hchain 17 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioc 17 50).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 13 ∣ (v - 1) ∧
              ¬ 17 ∣ (v - 1) ∧
              ((2304 - 2210) * v - 2304) ∣ (2304 * v - 2304 + 2) ∧
              Nat.Prime ((2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304)) ∧
              v < (2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
            hp4, hch3_5, hch3_13, hch3_17, hdvd,
            by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
        have hempty : (Finset.Ioc 17 50).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 13 ∣ (v - 1) ∧
              ¬ 17 ∣ (v - 1) ∧
              ((2304 - 2210) * v - 2304) ∣ (2304 * v - 2304 + 2) ∧
              Nat.Prime ((2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304)) ∧
              v < (2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304))
            = ∅ := by native_decide
        rw [hempty] at hmem3
        simp at hmem3
      · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- p3 = 19
      have heq3 : 2592 * ((p4 - 1) * (p5 - 1))
          = 2470 * (p4 * p5) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hs2 : 2 ≤ p4 := by omega
      have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
      have hshi : p4 ≤ 43 := by nlinarith [hbnd]
      by_cases hden : 2592 < (2592 - 2470) * p4
      · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
        have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
          hchain 5 p4 (by norm_num) hp4 hd1 hd4
        have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
          hchain 13 p4 (by norm_num) hp4 hd2 hd4
        have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
          hchain 19 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioc 19 43).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 13 ∣ (v - 1) ∧
              ¬ 19 ∣ (v - 1) ∧
              ((2592 - 2470) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
              Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592)) ∧
              v < (2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
            hp4, hch3_5, hch3_13, hch3_19, hdvd,
            by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
        have hempty : (Finset.Ioc 19 43).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 13 ∣ (v - 1) ∧
              ¬ 19 ∣ (v - 1) ∧
              ((2592 - 2470) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
              Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592)) ∧
              v < (2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592))
            = ∅ := by native_decide
        rw [hempty] at hmem3
        simp at hmem3
      · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- p3 = 23
      have heq3 : 3168 * ((p4 - 1) * (p5 - 1))
          = 2990 * (p4 * p5) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hs2 : 2 ≤ p4 := by omega
      have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
      have hshi : p4 ≤ 37 := by nlinarith [hbnd]
      by_cases hden : 3168 < (3168 - 2990) * p4
      · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
        have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
          hchain 5 p4 (by norm_num) hp4 hd1 hd4
        have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
          hchain 13 p4 (by norm_num) hp4 hd2 hd4
        have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
          hchain 23 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioc 23 37).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 13 ∣ (v - 1) ∧
              ¬ 23 ∣ (v - 1) ∧
              ((3168 - 2990) * v - 3168) ∣ (3168 * v - 3168 + 2) ∧
              Nat.Prime ((3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168)) ∧
              v < (3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
            hp4, hch3_5, hch3_13, hch3_23, hdvd,
            by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
        have hempty : (Finset.Ioc 23 37).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 13 ∣ (v - 1) ∧
              ¬ 23 ∣ (v - 1) ∧
              ((3168 - 2990) * v - 3168) ∣ (3168 * v - 3168 + 2) ∧
              Nat.Prime ((3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168)) ∧
              v < (3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168))
            = ∅ := by native_decide
        rw [hempty] at hmem3
        simp at hmem3
      · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- p3 = 29
      have heq3 : 4032 * ((p4 - 1) * (p5 - 1))
          = 3770 * (p4 * p5) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hs2 : 2 ≤ p4 := by omega
      have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
      have hshi : p4 ≤ 32 := by nlinarith [hbnd]
      by_cases hden : 4032 < (4032 - 3770) * p4
      · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
        have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
          hchain 5 p4 (by norm_num) hp4 hd1 hd4
        have hch3_13 : ¬ (13:ℕ) ∣ (p4 - 1) :=
          hchain 13 p4 (by norm_num) hp4 hd2 hd4
        have hch3_29 : ¬ (29:ℕ) ∣ (p4 - 1) :=
          hchain 29 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioc 29 32).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 13 ∣ (v - 1) ∧
              ¬ 29 ∣ (v - 1) ∧
              ((4032 - 3770) * v - 4032) ∣ (4032 * v - 4032 + 2) ∧
              Nat.Prime ((4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032)) ∧
              v < (4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
            hp4, hch3_5, hch3_13, hch3_29, hdvd,
            by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
        have hempty : (Finset.Ioc 29 32).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 13 ∣ (v - 1) ∧
              ¬ 29 ∣ (v - 1) ∧
              ((4032 - 3770) * v - 4032) ∣ (4032 * v - 4032 + 2) ∧
              Nat.Prime ((4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032)) ∧
              v < (4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032))
            = ∅ := by native_decide
        rw [hempty] at hmem3
        simp at hmem3
      · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
  · -- p2 = 17
    have heq2 : 192 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
        = 170 * (p3 * (p4 * p5)) + 2 := by
      ring_nf at heq1 ⊢
      omega
    have hcap2 : p3 < 29 := by
      by_contra hge
      exact cap_kill_3 (c := 29) (by norm_num) (by norm_num) (by omega)
        h3.le h4.le heq2
    have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
      hchain 5 p3 (by norm_num) hp3 hd1 hd3
    have hch2_17 : ¬ (17:ℕ) ∣ (p3 - 1) :=
      hchain 17 p3 (by norm_num) hp3 hd2 hd3
    have hmem2 : p3 ∈ (Finset.Ioo 17 29).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_17⟩
    have hset2 : (Finset.Ioo 17 29).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1))
        = ({19, 23} : Finset ℕ) := by native_decide
    rw [hset2] at hmem2
    fin_cases hmem2
    · -- p3 = 19
      have heq3 : 3456 * ((p4 - 1) * (p5 - 1))
          = 3230 * (p4 * p5) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hs2 : 2 ≤ p4 := by omega
      have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
      have hshi : p4 ≤ 32 := by nlinarith [hbnd]
      by_cases hden : 3456 < (3456 - 3230) * p4
      · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
        have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
          hchain 5 p4 (by norm_num) hp4 hd1 hd4
        have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
          hchain 17 p4 (by norm_num) hp4 hd2 hd4
        have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
          hchain 19 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioc 19 32).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 17 ∣ (v - 1) ∧
              ¬ 19 ∣ (v - 1) ∧
              ((3456 - 3230) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
              Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456)) ∧
              v < (3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
            hp4, hch3_5, hch3_17, hch3_19, hdvd,
            by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
        have hempty : (Finset.Ioc 19 32).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 17 ∣ (v - 1) ∧
              ¬ 19 ∣ (v - 1) ∧
              ((3456 - 3230) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
              Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456)) ∧
              v < (3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456))
            = ∅ := by native_decide
        rw [hempty] at hmem3
        simp at hmem3
      · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- p3 = 23
      have heq3 : 4224 * ((p4 - 1) * (p5 - 1))
          = 3910 * (p4 * p5) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hs2 : 2 ≤ p4 := by omega
      have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
      have hshi : p4 ≤ 28 := by nlinarith [hbnd]
      by_cases hden : 4224 < (4224 - 3910) * p4
      · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
        have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
          hchain 5 p4 (by norm_num) hp4 hd1 hd4
        have hch3_17 : ¬ (17:ℕ) ∣ (p4 - 1) :=
          hchain 17 p4 (by norm_num) hp4 hd2 hd4
        have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
          hchain 23 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioc 23 28).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 17 ∣ (v - 1) ∧
              ¬ 23 ∣ (v - 1) ∧
              ((4224 - 3910) * v - 4224) ∣ (4224 * v - 4224 + 2) ∧
              Nat.Prime ((4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224)) ∧
              v < (4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
            hp4, hch3_5, hch3_17, hch3_23, hdvd,
            by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
        have hempty : (Finset.Ioc 23 28).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 17 ∣ (v - 1) ∧
              ¬ 23 ∣ (v - 1) ∧
              ((4224 - 3910) * v - 4224) ∣ (4224 * v - 4224 + 2) ∧
              Nat.Prime ((4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224)) ∧
              v < (4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224))
            = ∅ := by native_decide
        rw [hempty] at hmem3
        simp at hmem3
      · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
  · -- p2 = 19
    have heq2 : 216 * ((p3 - 1) * ((p4 - 1) * (p5 - 1)))
        = 190 * (p3 * (p4 * p5)) + 2 := by
      ring_nf at heq1 ⊢
      omega
    have hcap2 : p3 < 29 := by
      by_contra hge
      exact cap_kill_3 (c := 29) (by norm_num) (by norm_num) (by omega)
        h3.le h4.le heq2
    have hch2_5 : ¬ (5:ℕ) ∣ (p3 - 1) :=
      hchain 5 p3 (by norm_num) hp3 hd1 hd3
    have hch2_19 : ¬ (19:ℕ) ∣ (p3 - 1) :=
      hchain 19 p3 (by norm_num) hp3 hd2 hd3
    have hmem2 : p3 ∈ (Finset.Ioo 19 29).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hp3, hch2_5, hch2_19⟩
    have hset2 : (Finset.Ioo 19 29).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
        = ({23} : Finset ℕ) := by native_decide
    rw [hset2] at hmem2
    fin_cases hmem2
    · -- p3 = 23
      have heq3 : 4752 * ((p4 - 1) * (p5 - 1))
          = 4370 * (p4 * p5) + 2 := by
        ring_nf at heq2 ⊢
        omega
      have hs2 : 2 ≤ p4 := by omega
      have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
      have hshi : p4 ≤ 26 := by nlinarith [hbnd]
      by_cases hden : 4752 < (4752 - 4370) * p4
      · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
        have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
          hchain 5 p4 (by norm_num) hp4 hd1 hd4
        have hch3_19 : ¬ (19:ℕ) ∣ (p4 - 1) :=
          hchain 19 p4 (by norm_num) hp4 hd2 hd4
        have hch3_23 : ¬ (23:ℕ) ∣ (p4 - 1) :=
          hchain 23 p4 (by norm_num) hp4 hd3 hd4
        have hmem3 : p4 ∈ (Finset.Ioc 23 26).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 19 ∣ (v - 1) ∧
              ¬ 23 ∣ (v - 1) ∧
              ((4752 - 4370) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
              Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752)) ∧
              v < (4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752)) :=
          Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
            hp4, hch3_5, hch3_19, hch3_23, hdvd,
            by rw [htval]; exact hp5, by rw [htval]; exact h4⟩
        have hempty : (Finset.Ioc 23 26).filter (fun v =>
              Nat.Prime v ∧
              ¬ 5 ∣ (v - 1) ∧
              ¬ 19 ∣ (v - 1) ∧
              ¬ 23 ∣ (v - 1) ∧
              ((4752 - 4370) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
              Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752)) ∧
              v < (4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752))
            = ∅ := by native_decide
        rw [hempty] at hmem3
        simp at hmem3
      · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)

end EG411Structure