-- AUTO-GENERATED by oracle/data_engine/omega_ladder/codegen.py (emit_lean_proof_multifile).
-- Certified kill-tree for omega = 6: 3*phi(n) = 2n+2 has NO solution with 6 distinct prime factors.
-- Part of a genuinely parallel-compilable cross-file split -- see emit_lean_proof_multifile's docstring.
-- Chunk 3/5 (omega6_chunk_5): LEAF -- depends only on OmegaTreeSupport/SolutionStructure,
-- never on a sibling chunk. Safe to compile in parallel with every other leaf chunk.
import SolutionStructure
import OmegaTreeSupport

namespace EG411Structure

set_option linter.style.nativeDecide false

set_option maxRecDepth 8000 in
set_option maxHeartbeats 0 in
theorem omega6_chunk_5 (n : ℕ) (hn : 3 * Nat.totient n = 2 * n + 2)
    (p4 p5 p6 : ℕ) (hp4 : p4.Prime) (hp5 : p5.Prime) (hp6 : p6.Prime)
    (h3 : (53:ℕ) < p4) (h4 : p4 < p5) (h5 : p5 < p6)
    (hd1 : (5:ℕ) ∣ n) (hd2 : (7:ℕ) ∣ n) (hd3 : (53:ℕ) ∣ n) (hd4 : p4 ∣ n) (hd5 : p5 ∣ n)
    (heq3 : 3744 * ((p4 - 1) * ((p5 - 1) * (p6 - 1))) = 3710 * (p4 * (p5 * p6)) + 2) : False := by
  have hchain := solution_no_prime_chain hn
  have hcap3 : p4 < 331 := by
    by_contra hge
    exact cap_kill_3 (c := 331) (by norm_num) (by norm_num) (by omega)
      h4.le h5.le heq3
  have hch3_5 : ¬ (5:ℕ) ∣ (p4 - 1) :=
    hchain 5 p4 (by norm_num) hp4 hd1 hd4
  have hch3_7 : ¬ (7:ℕ) ∣ (p4 - 1) :=
    hchain 7 p4 (by norm_num) hp4 hd2 hd4
  have hch3_53 : ¬ (53:ℕ) ∣ (p4 - 1) :=
    hchain 53 p4 (by norm_num) hp4 hd3 hd4
  have hmem3 : p4 ∈ (Finset.Ioo 53 331).filter
      (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 53 ∣ (v - 1)) :=
    Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap3⟩, hp4, hch3_5, hch3_7, hch3_53⟩
  have hset3 : (Finset.Ioo 53 331).filter
      (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 53 ∣ (v - 1))
      = ({59, 67, 73, 79, 83, 89, 97, 103,
          109, 137, 139, 149, 157, 163, 167, 173, 179, 193, 199, 223, 227, 229, 233, 257, 263, 269, 277, 283, 293, 307, 313, 317} : Finset ℕ) := by native_decide
  rw [hset3] at hmem3
  fin_cases hmem3
  · -- p4 = 59
    have heq4 : 217152 * ((p5 - 1) * (p6 - 1))
        = 218890 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 67
    have heq4 : 247104 * ((p5 - 1) * (p6 - 1))
        = 248570 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 73
    have heq4 : 269568 * ((p5 - 1) * (p6 - 1))
        = 270830 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 79
    have heq4 : 292032 * ((p5 - 1) * (p6 - 1))
        = 293090 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 83
    have heq4 : 307008 * ((p5 - 1) * (p6 - 1))
        = 307930 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 89
    have heq4 : 329472 * ((p5 - 1) * (p6 - 1))
        = 330190 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 97
    have heq4 : 359424 * ((p5 - 1) * (p6 - 1))
        = 359870 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 103
    have heq4 : 381888 * ((p5 - 1) * (p6 - 1))
        = 382130 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 109
    have heq4 : 404352 * ((p5 - 1) * (p6 - 1))
        = 404390 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    exact dead_kill_2 (by norm_num) heq4
  · -- p4 = 137
    have heq4 : 509184 * ((p5 - 1) * (p6 - 1))
        = 508270 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 1115 := by nlinarith [hbnd]
    by_cases hden : 509184 < (509184 - 508270) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_137 : ¬ (137:ℕ) ∣ (p5 - 1) :=
        hchain 137 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 137 1115).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 137 ∣ (v - 1) ∧
            ((509184 - 508270) * v - 509184) ∣ (509184 * v - 509184 + 2) ∧
            Nat.Prime ((509184 * v - 509184 + 2) / ((509184 - 508270) * v - 509184)) ∧
            v < (509184 * v - 509184 + 2) / ((509184 - 508270) * v - 509184)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_137, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 137 1115).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 137 ∣ (v - 1) ∧
            ((509184 - 508270) * v - 509184) ∣ (509184 * v - 509184 + 2) ∧
            Nat.Prime ((509184 * v - 509184 + 2) / ((509184 - 508270) * v - 509184)) ∧
            v < (509184 * v - 509184 + 2) / ((509184 - 508270) * v - 509184))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 139
    have heq4 : 516672 * ((p5 - 1) * (p6 - 1))
        = 515690 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 1053 := by nlinarith [hbnd]
    by_cases hden : 516672 < (516672 - 515690) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_139 : ¬ (139:ℕ) ∣ (p5 - 1) :=
        hchain 139 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 139 1053).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 139 ∣ (v - 1) ∧
            ((516672 - 515690) * v - 516672) ∣ (516672 * v - 516672 + 2) ∧
            Nat.Prime ((516672 * v - 516672 + 2) / ((516672 - 515690) * v - 516672)) ∧
            v < (516672 * v - 516672 + 2) / ((516672 - 515690) * v - 516672)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_139, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 139 1053).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 139 ∣ (v - 1) ∧
            ((516672 - 515690) * v - 516672) ∣ (516672 * v - 516672 + 2) ∧
            Nat.Prime ((516672 * v - 516672 + 2) / ((516672 - 515690) * v - 516672)) ∧
            v < (516672 * v - 516672 + 2) / ((516672 - 515690) * v - 516672))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 149
    have heq4 : 554112 * ((p5 - 1) * (p6 - 1))
        = 552790 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 839 := by nlinarith [hbnd]
    by_cases hden : 554112 < (554112 - 552790) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_149 : ¬ (149:ℕ) ∣ (p5 - 1) :=
        hchain 149 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 149 839).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 149 ∣ (v - 1) ∧
            ((554112 - 552790) * v - 554112) ∣ (554112 * v - 554112 + 2) ∧
            Nat.Prime ((554112 * v - 554112 + 2) / ((554112 - 552790) * v - 554112)) ∧
            v < (554112 * v - 554112 + 2) / ((554112 - 552790) * v - 554112)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_149, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 149 839).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 149 ∣ (v - 1) ∧
            ((554112 - 552790) * v - 554112) ∣ (554112 * v - 554112 + 2) ∧
            Nat.Prime ((554112 * v - 554112 + 2) / ((554112 - 552790) * v - 554112)) ∧
            v < (554112 * v - 554112 + 2) / ((554112 - 552790) * v - 554112))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 157
    have heq4 : 584064 * ((p5 - 1) * (p6 - 1))
        = 582470 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 734 := by nlinarith [hbnd]
    by_cases hden : 584064 < (584064 - 582470) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_157 : ¬ (157:ℕ) ∣ (p5 - 1) :=
        hchain 157 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 157 734).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 157 ∣ (v - 1) ∧
            ((584064 - 582470) * v - 584064) ∣ (584064 * v - 584064 + 2) ∧
            Nat.Prime ((584064 * v - 584064 + 2) / ((584064 - 582470) * v - 584064)) ∧
            v < (584064 * v - 584064 + 2) / ((584064 - 582470) * v - 584064)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_157, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 157 734).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 157 ∣ (v - 1) ∧
            ((584064 - 582470) * v - 584064) ∣ (584064 * v - 584064 + 2) ∧
            Nat.Prime ((584064 * v - 584064 + 2) / ((584064 - 582470) * v - 584064)) ∧
            v < (584064 * v - 584064 + 2) / ((584064 - 582470) * v - 584064))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 163
    have heq4 : 606528 * ((p5 - 1) * (p6 - 1))
        = 604730 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 676 := by nlinarith [hbnd]
    by_cases hden : 606528 < (606528 - 604730) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_163 : ¬ (163:ℕ) ∣ (p5 - 1) :=
        hchain 163 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 163 676).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 163 ∣ (v - 1) ∧
            ((606528 - 604730) * v - 606528) ∣ (606528 * v - 606528 + 2) ∧
            Nat.Prime ((606528 * v - 606528 + 2) / ((606528 - 604730) * v - 606528)) ∧
            v < (606528 * v - 606528 + 2) / ((606528 - 604730) * v - 606528)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_163, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 163 676).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 163 ∣ (v - 1) ∧
            ((606528 - 604730) * v - 606528) ∣ (606528 * v - 606528 + 2) ∧
            Nat.Prime ((606528 * v - 606528 + 2) / ((606528 - 604730) * v - 606528)) ∧
            v < (606528 * v - 606528 + 2) / ((606528 - 604730) * v - 606528))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 167
    have heq4 : 621504 * ((p5 - 1) * (p6 - 1))
        = 619570 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 644 := by nlinarith [hbnd]
    by_cases hden : 621504 < (621504 - 619570) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_167 : ¬ (167:ℕ) ∣ (p5 - 1) :=
        hchain 167 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 167 644).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 167 ∣ (v - 1) ∧
            ((621504 - 619570) * v - 621504) ∣ (621504 * v - 621504 + 2) ∧
            Nat.Prime ((621504 * v - 621504 + 2) / ((621504 - 619570) * v - 621504)) ∧
            v < (621504 * v - 621504 + 2) / ((621504 - 619570) * v - 621504)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_167, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 167 644).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 167 ∣ (v - 1) ∧
            ((621504 - 619570) * v - 621504) ∣ (621504 * v - 621504 + 2) ∧
            Nat.Prime ((621504 * v - 621504 + 2) / ((621504 - 619570) * v - 621504)) ∧
            v < (621504 * v - 621504 + 2) / ((621504 - 619570) * v - 621504))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 173
    have heq4 : 643968 * ((p5 - 1) * (p6 - 1))
        = 641830 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 603 := by nlinarith [hbnd]
    by_cases hden : 643968 < (643968 - 641830) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_173 : ¬ (173:ℕ) ∣ (p5 - 1) :=
        hchain 173 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 173 603).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 173 ∣ (v - 1) ∧
            ((643968 - 641830) * v - 643968) ∣ (643968 * v - 643968 + 2) ∧
            Nat.Prime ((643968 * v - 643968 + 2) / ((643968 - 641830) * v - 643968)) ∧
            v < (643968 * v - 643968 + 2) / ((643968 - 641830) * v - 643968)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_173, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 173 603).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 173 ∣ (v - 1) ∧
            ((643968 - 641830) * v - 643968) ∣ (643968 * v - 643968 + 2) ∧
            Nat.Prime ((643968 * v - 643968 + 2) / ((643968 - 641830) * v - 643968)) ∧
            v < (643968 * v - 643968 + 2) / ((643968 - 641830) * v - 643968))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 179
    have heq4 : 666432 * ((p5 - 1) * (p6 - 1))
        = 664090 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 570 := by nlinarith [hbnd]
    by_cases hden : 666432 < (666432 - 664090) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_179 : ¬ (179:ℕ) ∣ (p5 - 1) :=
        hchain 179 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 179 570).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 179 ∣ (v - 1) ∧
            ((666432 - 664090) * v - 666432) ∣ (666432 * v - 666432 + 2) ∧
            Nat.Prime ((666432 * v - 666432 + 2) / ((666432 - 664090) * v - 666432)) ∧
            v < (666432 * v - 666432 + 2) / ((666432 - 664090) * v - 666432)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_179, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 179 570).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 179 ∣ (v - 1) ∧
            ((666432 - 664090) * v - 666432) ∣ (666432 * v - 666432 + 2) ∧
            Nat.Prime ((666432 * v - 666432 + 2) / ((666432 - 664090) * v - 666432)) ∧
            v < (666432 * v - 666432 + 2) / ((666432 - 664090) * v - 666432))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 193
    have heq4 : 718848 * ((p5 - 1) * (p6 - 1))
        = 716030 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 511 := by nlinarith [hbnd]
    by_cases hden : 718848 < (718848 - 716030) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_193 : ¬ (193:ℕ) ∣ (p5 - 1) :=
        hchain 193 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 193 511).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 193 ∣ (v - 1) ∧
            ((718848 - 716030) * v - 718848) ∣ (718848 * v - 718848 + 2) ∧
            Nat.Prime ((718848 * v - 718848 + 2) / ((718848 - 716030) * v - 718848)) ∧
            v < (718848 * v - 718848 + 2) / ((718848 - 716030) * v - 718848)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_193, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 193 511).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 193 ∣ (v - 1) ∧
            ((718848 - 716030) * v - 718848) ∣ (718848 * v - 718848 + 2) ∧
            Nat.Prime ((718848 * v - 718848 + 2) / ((718848 - 716030) * v - 718848)) ∧
            v < (718848 * v - 718848 + 2) / ((718848 - 716030) * v - 718848))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 199
    have heq4 : 741312 * ((p5 - 1) * (p6 - 1))
        = 738290 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 492 := by nlinarith [hbnd]
    by_cases hden : 741312 < (741312 - 738290) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_199 : ¬ (199:ℕ) ∣ (p5 - 1) :=
        hchain 199 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 199 492).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 199 ∣ (v - 1) ∧
            ((741312 - 738290) * v - 741312) ∣ (741312 * v - 741312 + 2) ∧
            Nat.Prime ((741312 * v - 741312 + 2) / ((741312 - 738290) * v - 741312)) ∧
            v < (741312 * v - 741312 + 2) / ((741312 - 738290) * v - 741312)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_199, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 199 492).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 199 ∣ (v - 1) ∧
            ((741312 - 738290) * v - 741312) ∣ (741312 * v - 741312 + 2) ∧
            Nat.Prime ((741312 * v - 741312 + 2) / ((741312 - 738290) * v - 741312)) ∧
            v < (741312 * v - 741312 + 2) / ((741312 - 738290) * v - 741312))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 223
    have heq4 : 831168 * ((p5 - 1) * (p6 - 1))
        = 827330 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 434 := by nlinarith [hbnd]
    by_cases hden : 831168 < (831168 - 827330) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_223 : ¬ (223:ℕ) ∣ (p5 - 1) :=
        hchain 223 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 223 434).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 223 ∣ (v - 1) ∧
            ((831168 - 827330) * v - 831168) ∣ (831168 * v - 831168 + 2) ∧
            Nat.Prime ((831168 * v - 831168 + 2) / ((831168 - 827330) * v - 831168)) ∧
            v < (831168 * v - 831168 + 2) / ((831168 - 827330) * v - 831168)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_223, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 223 434).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 223 ∣ (v - 1) ∧
            ((831168 - 827330) * v - 831168) ∣ (831168 * v - 831168 + 2) ∧
            Nat.Prime ((831168 * v - 831168 + 2) / ((831168 - 827330) * v - 831168)) ∧
            v < (831168 * v - 831168 + 2) / ((831168 - 827330) * v - 831168))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 227
    have heq4 : 846144 * ((p5 - 1) * (p6 - 1))
        = 842170 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 427 := by nlinarith [hbnd]
    by_cases hden : 846144 < (846144 - 842170) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_227 : ¬ (227:ℕ) ∣ (p5 - 1) :=
        hchain 227 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 227 427).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 227 ∣ (v - 1) ∧
            ((846144 - 842170) * v - 846144) ∣ (846144 * v - 846144 + 2) ∧
            Nat.Prime ((846144 * v - 846144 + 2) / ((846144 - 842170) * v - 846144)) ∧
            v < (846144 * v - 846144 + 2) / ((846144 - 842170) * v - 846144)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_227, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 227 427).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 227 ∣ (v - 1) ∧
            ((846144 - 842170) * v - 846144) ∣ (846144 * v - 846144 + 2) ∧
            Nat.Prime ((846144 * v - 846144 + 2) / ((846144 - 842170) * v - 846144)) ∧
            v < (846144 * v - 846144 + 2) / ((846144 - 842170) * v - 846144))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 229
    have heq4 : 853632 * ((p5 - 1) * (p6 - 1))
        = 849590 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 423 := by nlinarith [hbnd]
    by_cases hden : 853632 < (853632 - 849590) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_229 : ¬ (229:ℕ) ∣ (p5 - 1) :=
        hchain 229 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 229 423).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 229 ∣ (v - 1) ∧
            ((853632 - 849590) * v - 853632) ∣ (853632 * v - 853632 + 2) ∧
            Nat.Prime ((853632 * v - 853632 + 2) / ((853632 - 849590) * v - 853632)) ∧
            v < (853632 * v - 853632 + 2) / ((853632 - 849590) * v - 853632)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_229, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 229 423).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 229 ∣ (v - 1) ∧
            ((853632 - 849590) * v - 853632) ∣ (853632 * v - 853632 + 2) ∧
            Nat.Prime ((853632 * v - 853632 + 2) / ((853632 - 849590) * v - 853632)) ∧
            v < (853632 * v - 853632 + 2) / ((853632 - 849590) * v - 853632))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 233
    have heq4 : 868608 * ((p5 - 1) * (p6 - 1))
        = 864430 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 417 := by nlinarith [hbnd]
    by_cases hden : 868608 < (868608 - 864430) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_233 : ¬ (233:ℕ) ∣ (p5 - 1) :=
        hchain 233 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 233 417).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 233 ∣ (v - 1) ∧
            ((868608 - 864430) * v - 868608) ∣ (868608 * v - 868608 + 2) ∧
            Nat.Prime ((868608 * v - 868608 + 2) / ((868608 - 864430) * v - 868608)) ∧
            v < (868608 * v - 868608 + 2) / ((868608 - 864430) * v - 868608)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_233, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 233 417).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 233 ∣ (v - 1) ∧
            ((868608 - 864430) * v - 868608) ∣ (868608 * v - 868608 + 2) ∧
            Nat.Prime ((868608 * v - 868608 + 2) / ((868608 - 864430) * v - 868608)) ∧
            v < (868608 * v - 868608 + 2) / ((868608 - 864430) * v - 868608))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 257
    have heq4 : 958464 * ((p5 - 1) * (p6 - 1))
        = 953470 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 385 := by nlinarith [hbnd]
    by_cases hden : 958464 < (958464 - 953470) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_257 : ¬ (257:ℕ) ∣ (p5 - 1) :=
        hchain 257 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 257 385).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 257 ∣ (v - 1) ∧
            ((958464 - 953470) * v - 958464) ∣ (958464 * v - 958464 + 2) ∧
            Nat.Prime ((958464 * v - 958464 + 2) / ((958464 - 953470) * v - 958464)) ∧
            v < (958464 * v - 958464 + 2) / ((958464 - 953470) * v - 958464)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_257, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 257 385).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 257 ∣ (v - 1) ∧
            ((958464 - 953470) * v - 958464) ∣ (958464 * v - 958464 + 2) ∧
            Nat.Prime ((958464 * v - 958464 + 2) / ((958464 - 953470) * v - 958464)) ∧
            v < (958464 * v - 958464 + 2) / ((958464 - 953470) * v - 958464))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 263
    have heq4 : 980928 * ((p5 - 1) * (p6 - 1))
        = 975730 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 378 := by nlinarith [hbnd]
    by_cases hden : 980928 < (980928 - 975730) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_263 : ¬ (263:ℕ) ∣ (p5 - 1) :=
        hchain 263 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 263 378).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 263 ∣ (v - 1) ∧
            ((980928 - 975730) * v - 980928) ∣ (980928 * v - 980928 + 2) ∧
            Nat.Prime ((980928 * v - 980928 + 2) / ((980928 - 975730) * v - 980928)) ∧
            v < (980928 * v - 980928 + 2) / ((980928 - 975730) * v - 980928)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_263, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 263 378).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 263 ∣ (v - 1) ∧
            ((980928 - 975730) * v - 980928) ∣ (980928 * v - 980928 + 2) ∧
            Nat.Prime ((980928 * v - 980928 + 2) / ((980928 - 975730) * v - 980928)) ∧
            v < (980928 * v - 980928 + 2) / ((980928 - 975730) * v - 980928))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 269
    have heq4 : 1003392 * ((p5 - 1) * (p6 - 1))
        = 997990 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 372 := by nlinarith [hbnd]
    by_cases hden : 1003392 < (1003392 - 997990) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_269 : ¬ (269:ℕ) ∣ (p5 - 1) :=
        hchain 269 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 269 372).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 269 ∣ (v - 1) ∧
            ((1003392 - 997990) * v - 1003392) ∣ (1003392 * v - 1003392 + 2) ∧
            Nat.Prime ((1003392 * v - 1003392 + 2) / ((1003392 - 997990) * v - 1003392)) ∧
            v < (1003392 * v - 1003392 + 2) / ((1003392 - 997990) * v - 1003392)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_269, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 269 372).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 269 ∣ (v - 1) ∧
            ((1003392 - 997990) * v - 1003392) ∣ (1003392 * v - 1003392 + 2) ∧
            Nat.Prime ((1003392 * v - 1003392 + 2) / ((1003392 - 997990) * v - 1003392)) ∧
            v < (1003392 * v - 1003392 + 2) / ((1003392 - 997990) * v - 1003392))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 277
    have heq4 : 1033344 * ((p5 - 1) * (p6 - 1))
        = 1027670 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 365 := by nlinarith [hbnd]
    by_cases hden : 1033344 < (1033344 - 1027670) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_277 : ¬ (277:ℕ) ∣ (p5 - 1) :=
        hchain 277 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 277 365).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 277 ∣ (v - 1) ∧
            ((1033344 - 1027670) * v - 1033344) ∣ (1033344 * v - 1033344 + 2) ∧
            Nat.Prime ((1033344 * v - 1033344 + 2) / ((1033344 - 1027670) * v - 1033344)) ∧
            v < (1033344 * v - 1033344 + 2) / ((1033344 - 1027670) * v - 1033344)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_277, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 277 365).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 277 ∣ (v - 1) ∧
            ((1033344 - 1027670) * v - 1033344) ∣ (1033344 * v - 1033344 + 2) ∧
            Nat.Prime ((1033344 * v - 1033344 + 2) / ((1033344 - 1027670) * v - 1033344)) ∧
            v < (1033344 * v - 1033344 + 2) / ((1033344 - 1027670) * v - 1033344))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 283
    have heq4 : 1055808 * ((p5 - 1) * (p6 - 1))
        = 1049930 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 360 := by nlinarith [hbnd]
    by_cases hden : 1055808 < (1055808 - 1049930) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_283 : ¬ (283:ℕ) ∣ (p5 - 1) :=
        hchain 283 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 283 360).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 283 ∣ (v - 1) ∧
            ((1055808 - 1049930) * v - 1055808) ∣ (1055808 * v - 1055808 + 2) ∧
            Nat.Prime ((1055808 * v - 1055808 + 2) / ((1055808 - 1049930) * v - 1055808)) ∧
            v < (1055808 * v - 1055808 + 2) / ((1055808 - 1049930) * v - 1055808)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_283, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 283 360).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 283 ∣ (v - 1) ∧
            ((1055808 - 1049930) * v - 1055808) ∣ (1055808 * v - 1055808 + 2) ∧
            Nat.Prime ((1055808 * v - 1055808 + 2) / ((1055808 - 1049930) * v - 1055808)) ∧
            v < (1055808 * v - 1055808 + 2) / ((1055808 - 1049930) * v - 1055808))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 293
    have heq4 : 1093248 * ((p5 - 1) * (p6 - 1))
        = 1087030 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 353 := by nlinarith [hbnd]
    by_cases hden : 1093248 < (1093248 - 1087030) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_293 : ¬ (293:ℕ) ∣ (p5 - 1) :=
        hchain 293 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 293 353).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 293 ∣ (v - 1) ∧
            ((1093248 - 1087030) * v - 1093248) ∣ (1093248 * v - 1093248 + 2) ∧
            Nat.Prime ((1093248 * v - 1093248 + 2) / ((1093248 - 1087030) * v - 1093248)) ∧
            v < (1093248 * v - 1093248 + 2) / ((1093248 - 1087030) * v - 1093248)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_293, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 293 353).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 293 ∣ (v - 1) ∧
            ((1093248 - 1087030) * v - 1093248) ∣ (1093248 * v - 1093248 + 2) ∧
            Nat.Prime ((1093248 * v - 1093248 + 2) / ((1093248 - 1087030) * v - 1093248)) ∧
            v < (1093248 * v - 1093248 + 2) / ((1093248 - 1087030) * v - 1093248))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 307
    have heq4 : 1145664 * ((p5 - 1) * (p6 - 1))
        = 1138970 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 343 := by nlinarith [hbnd]
    by_cases hden : 1145664 < (1145664 - 1138970) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_307 : ¬ (307:ℕ) ∣ (p5 - 1) :=
        hchain 307 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 307 343).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 307 ∣ (v - 1) ∧
            ((1145664 - 1138970) * v - 1145664) ∣ (1145664 * v - 1145664 + 2) ∧
            Nat.Prime ((1145664 * v - 1145664 + 2) / ((1145664 - 1138970) * v - 1145664)) ∧
            v < (1145664 * v - 1145664 + 2) / ((1145664 - 1138970) * v - 1145664)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_307, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 307 343).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 307 ∣ (v - 1) ∧
            ((1145664 - 1138970) * v - 1145664) ∣ (1145664 * v - 1145664 + 2) ∧
            Nat.Prime ((1145664 * v - 1145664 + 2) / ((1145664 - 1138970) * v - 1145664)) ∧
            v < (1145664 * v - 1145664 + 2) / ((1145664 - 1138970) * v - 1145664))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 313
    have heq4 : 1168128 * ((p5 - 1) * (p6 - 1))
        = 1161230 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 340 := by nlinarith [hbnd]
    by_cases hden : 1168128 < (1168128 - 1161230) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_313 : ¬ (313:ℕ) ∣ (p5 - 1) :=
        hchain 313 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 313 340).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 313 ∣ (v - 1) ∧
            ((1168128 - 1161230) * v - 1168128) ∣ (1168128 * v - 1168128 + 2) ∧
            Nat.Prime ((1168128 * v - 1168128 + 2) / ((1168128 - 1161230) * v - 1168128)) ∧
            v < (1168128 * v - 1168128 + 2) / ((1168128 - 1161230) * v - 1168128)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_313, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 313 340).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 313 ∣ (v - 1) ∧
            ((1168128 - 1161230) * v - 1168128) ∣ (1168128 * v - 1168128 + 2) ∧
            Nat.Prime ((1168128 * v - 1168128 + 2) / ((1168128 - 1161230) * v - 1168128)) ∧
            v < (1168128 * v - 1168128 + 2) / ((1168128 - 1161230) * v - 1168128))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)
  · -- p4 = 317
    have heq4 : 1183104 * ((p5 - 1) * (p6 - 1))
        = 1176070 * (p5 * p6) + 2 := by
      ring_nf at heq3 ⊢
      omega
    have hs2 : 2 ≤ p5 := by omega
    have hbnd := terminal_bound (by norm_num) heq4 h5 hs2
    have hshi : p5 ≤ 337 := by nlinarith [hbnd]
    by_cases hden : 1183104 < (1183104 - 1176070) * p5
    · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq4 h5 hs2 hden
      have hch4_5 : ¬ (5:ℕ) ∣ (p5 - 1) :=
        hchain 5 p5 (by norm_num) hp5 hd1 hd5
      have hch4_7 : ¬ (7:ℕ) ∣ (p5 - 1) :=
        hchain 7 p5 (by norm_num) hp5 hd2 hd5
      have hch4_53 : ¬ (53:ℕ) ∣ (p5 - 1) :=
        hchain 53 p5 (by norm_num) hp5 hd3 hd5
      have hch4_317 : ¬ (317:ℕ) ∣ (p5 - 1) :=
        hchain 317 p5 (by norm_num) hp5 hd4 hd5
      have hmem4 : p5 ∈ (Finset.Ioc 317 337).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 317 ∣ (v - 1) ∧
            ((1183104 - 1176070) * v - 1183104) ∣ (1183104 * v - 1183104 + 2) ∧
            Nat.Prime ((1183104 * v - 1183104 + 2) / ((1183104 - 1176070) * v - 1183104)) ∧
            v < (1183104 * v - 1183104 + 2) / ((1183104 - 1176070) * v - 1183104)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
          hp5, hch4_5, hch4_7, hch4_53, hch4_317, hdvd,
          by rw [htval]; exact hp6, by rw [htval]; exact h5⟩
      have hempty : (Finset.Ioc 317 337).filter (fun v =>
            Nat.Prime v ∧
            ¬ 5 ∣ (v - 1) ∧
            ¬ 7 ∣ (v - 1) ∧
            ¬ 53 ∣ (v - 1) ∧
            ¬ 317 ∣ (v - 1) ∧
            ((1183104 - 1176070) * v - 1183104) ∣ (1183104 * v - 1183104 + 2) ∧
            Nat.Prime ((1183104 * v - 1183104 + 2) / ((1183104 - 1176070) * v - 1183104)) ∧
            v < (1183104 * v - 1183104 + 2) / ((1183104 - 1176070) * v - 1183104))
          = ∅ := by native_decide
      rw [hempty] at hmem4
      simp at hmem4
    · exact terminal_low_kill (by norm_num) heq4 h5 hs2 (by omega)

end EG411Structure