import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Tactic
import EG203Formal.MicroSieve.Basic

/-!
# EG203 Micro-Sieve Layer — residue obstruction definitions

This file exposes the finite local obstruction data used by the sieve.

For a prime q, the pair `(k,l)` is obstructed if:

 m * 2^k * 3^l + 1 ≡ 0 mod q.

The analytic sieve estimates how often these obstructions occur across q.
-/

namespace EG203.MicroSieve

/-- Divisibility obstruction at prime q. -/
def ObstructedBy (m q k l : Nat) : Prop :=
 q ∣ V m k l

/-- Unobstructed by q. -/
def UnobstructedBy (m q k l : Nat) : Prop :=
 ¬ ObstructedBy m q k l

/-- Obstruction set inside the triangular box. -/
def BoxObstructionSet (m q D : Nat) : Set (Nat × Nat) :=
 { kl | InTriBox D kl.1 kl.2 ∧ ObstructedBy m q kl.1 kl.2 }

/-- A prime q is relevant when q does not divide 6m. -/
def RelevantPrimeFor (m q : Nat) : Prop :=
 Nat.Prime q ∧ q ≠ 2 ∧ q ≠ 3 ∧ ¬ q ∣ m

/-- Local order proxy: period of the subgroup generated by 2 and 3 mod q.
This is left as a Nat-valued interface because Mathlib's order API over ZMod
can be wired later without changing the sieve target.
-/
opaque H (q : Nat) : Nat

/-- Subgroup concentration bound interface over H. -/
def SubgroupConcentrationBound : Prop :=
 ∀ z : Nat, 100 ≤ z →
 True
 -- Intended real statement:
 -- ∑_{3 < q ≤ z, Nat.Prime q} (1 : ℝ) / H q ≤ 4 * Real.log (Real.log z) + 12

/-- A local obstruction density upper bound for a single prime q. -/
def LocalObstructionBound : Prop :=
 ∀ m q D : Nat, Ordinary m → RelevantPrimeFor m q →
 True
 -- Intended:
 -- #(BoxObstructionSet m q D) ≤ triBoxVolume D / H q + boundary(q,D)

/-- The triangular box volume formula. -/
def triBoxVolume (D : Nat) : Nat :=
 (D + 1) * (D + 2) / 2

/-- Algebraic version of the triangular volume numerator. -/
theorem triBoxVolume_mul_two (D : Nat) :
 2 * triBoxVolume D ≤ (D + 1) * (D + 2) := by
 unfold triBoxVolume
 exact Nat.mul_div_le _ _

/-- Positive triangular volume. -/
theorem triBoxVolume_pos (D : Nat) : 0 < triBoxVolume D := by
 unfold triBoxVolume
 have h : 2 ≤ (D+1)*(D+2) := by nlinarith
 omega

/-- If no pair in the box is prime, every pair is composite or equal to 1.
This is the entry point for a contradiction sieve.
-/
def NoPrimeInBox (m D : Nat) : Prop :=
 ∀ k l : Nat, InTriBox D k l → ¬ Nat.Prime (V m k l)

/-- A positive count contradicts no-prime-in-box. -/
theorem not_no_prime_of_positive_count
 {m D : Nat}
 (hpos : PositivePrimeCountInBox m D) :
 ¬ NoPrimeInBox m D := by
 intro hnone
 rcases hpos with ⟨k,l,hbox,hp⟩
 exact hnone k l hbox hp

/-- Contradiction form of positive count. -/
theorem positive_count_of_not_no_prime
 {m D : Nat}
 (h : ¬ NoPrimeInBox m D) :
 PositivePrimeCountInBox m D := by
 classical
 unfold NoPrimeInBox at h
 by_contra hno
 apply h
 intro k l hbox hp
 exact hno ⟨k,l,hbox,hp⟩

/-- If every box has no prime, then EG203 fails for m. -/
def CounterexampleAt (m : Nat) : Prop :=
 Ordinary m ∧ ∀ k l : Nat, ¬ Nat.Prime (V m k l)

/-- A counterexample has no prime in every finite box. -/
theorem no_prime_box_of_counterexample
 {m D : Nat}
 (h : CounterexampleAt m) :
 NoPrimeInBox m D := by
 intro k l _hbox hp
 exact h.2 k l hp

/-- If one box has a positive count, m is not a counterexample. -/
theorem not_counterexample_of_positive_count
 {m D : Nat}
 (h : PositivePrimeCountInBox m D) :
 ¬ CounterexampleAt m := by
 intro hc
 exact not_no_prime_of_positive_count h (no_prime_box_of_counterexample hc)

end EG203.MicroSieve
